  <div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
           <div class="page-header"><h1><a name="up"></a>Corpus c&egrave;muh&icirc;</h1></div>
     <div class="text-left"> <p class="intertitre">&nbsp;</p>
      <p class="intertitre">Fiche technique sur le <a href="../../ALC/Languages/Cemuhi_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false">c&egrave;muh&icirc;<img src="../../images/icones/info.gif" alt="a" width="15" height="15" border="0"></a></p>
      <p class="intertitre">&nbsp;</p>
      <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Cemuhî" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <ul class="liste-liens">
        <li><a href="#laiteron">Fleurs de laiteron de Pw&ouml;paat</a></li>
        <li><a href="#crabe">Le crabe et la fillette de Pwa&eacute;&eacute;to</a></li>
        <li><a href="#tortue">Tortue et les deux p&ecirc;cheuses</a></li>
        <li><a href="#ecailles">Les &eacute;cailles de poisson de Tiw&eacute;caal&egrave;</a></li>
        <li><a href="#large">Dui Dupaan et la fille du grand large</a></li>
        <li><a href="#coquillage">Le coquillage et les enfants</a></li>
        <li><a href="#oranger">Les enfants de l'oranger</a></li>
        <li><a href="#fruits">Les deux fruits sauvages</a></li>
        <li><a href="#anguille">L'anguille des Wic&egrave;</a></li>
        </ul>
      <p>&nbsp;</p>
      <p class="intertitre"><a name="laiteron"></a><a href="../corpus/show_text.php?id=crdo-CAM_FLEURS_SOUND&idref=crdo-CAM_FLEURS"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Fleurs de laiteron de Pw&ouml;paat</a><br>
Nouvelle-Cal&eacute;donie,        Poyes, 1965, Célina Daulo, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint"> Les deux femmes &quot;Fleurs de laiteron de Pw&ouml;paat&quot; p&ecirc;chent leurs anguilles, arrachent leurs taros, puis les font cuire une fois rentr&eacute;es &agrave; la maison. Survient l'ogresse A-wii-d&egrave;l&egrave;-apulip bien d&eacute;cid&eacute;e &agrave; leur subtiliser leur nourriture...</p>
      <p class="intertitre"><a name="crabe"></a><a href="../corpus/show_text.php?id=crdo-CAM_CRABE_SOUND&idref=crdo-CAM_CRABE"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Le crabe et la fillette de Pwa&eacute;&eacute;to</a><br>
Nouvelle-Cal&eacute;donie,        Poyes, 1965, Célina Daulo, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Histoire d'une fillette rest&eacute;e seule &agrave; la maison pendant que sa m&egrave;re est partie travailler dans les plantations. M&egrave;re Crabe en profite pour s'introduire aupr&egrave;s de la fillette, sous pr&eacute;texte de lui tenir compagnie. La fillette doit alors inventer un stratag&egrave;me pour se d&eacute;barasser de ce visiteur importun et quelque peu sadique...</p>
      <p class="intertitre"><a name="tortue"></a><a href="../corpus/show_text.php?id=crdo-CAM_TORTUE_SOUND&idref=crdo-CAM_TORTUE"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Tortue et les deux p&ecirc;cheuses</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
Nouvelle-Cal&eacute;donie, Poyes, 1965, Marie Daulo, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Les deux p&ecirc;cheuses dont la torche s'est &eacute;teinte esp&egrave;rent trouver du feu chez M&egrave;re Tortue. Mais celle-ci les &eacute;conduit et les deux femmes regagnent leur maison en t&acirc;tonnant dans l'obscurit&eacute;. Pour se venger, elles badigeonnent en noir les alentours de la demeure de M&egrave;re Tortue, en utilisant du charbon de gommier br&ucirc;l&eacute;. Plong&eacute;e dans les t&eacute;n&egrave;bres, M&egrave;re Tortue s'av&egrave;re bient&ocirc;t incapable de subvenir aux besoins de sa prog&eacute;niture...</p>
      <p class="intertitre"><a name="ecailles"></a><a href="../corpus/show_text.php?id=crdo-CAM_ECAIL_SOUND&idref=crdo-CAM_ECAIL"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Les &eacute;cailles de poisson de Tiw&eacute;caal&egrave;</a> <br>
        Nouvelle-Cal&eacute;donie, Vieux-Touho, 1965, Bernadette Tyèn, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Histoire de deux jeunes femmes: Ik&eacute; et Kaapo. Ik&eacute; part rejoindre Kaapo, sa soeur a&icirc;n&eacute;e, mari&eacute;e chez un chef de la c&ocirc;te ouest. Les festivit&eacute;s qui accompagnent la naissance de l'enfant de Kaapo tournent mal et les deux jeunes femmes rentrent en catastrophe chez elles, sur la c&ocirc;te est. Kaapo la soeur a&icirc;n&eacute;e vient &agrave; mourir mais elle continue de hanter les abords de l'habitation de sa soeur sous la forme d'une revenante ou d'un lochon d'eau douce pr&eacute;sent dans le puits. Dans les deux &eacute;pisodes qui composent cette histoire, la cadette est d&eacute;livr&eacute;e de ses tourments gr&acirc;ce &agrave; l'intervention de la divinit&eacute; mwak&eacute;n, auxiliaire des ma&icirc;tres du terrain dans la r&eacute;gion de Touho.</p>
      <p class="intertitre"><a name="large"></a><a href="../corpus/show_text.php?id=crdo-CAM_DUI_SOUND&idref=crdo-CAM_DUI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Dui Dupaan et la fille du grand large</a><br>
        Nouvelle-Cal&eacute;donie,
        Tiwa&eacute;, 1966, Jean-Baptiste Bova, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">L&eacute;gende c&egrave;muh&icirc; racont&eacute;e &agrave; Tiwa&eacute; en 1966 par Jean-Baptiste Bova, membre du clan des ma&icirc;tres du sol de la r&eacute;gion de Pwei, arri&egrave;re-pays de Touho. Elle reprend &agrave; travers un jeu simplifi&eacute; d'images la th&eacute;matique g&eacute;n&eacute;rale de l'organisation des chefferies de cette r&eacute;gion. Celle-ci s'appuie sur deux p&ocirc;les ici figur&eacute;s chacun par deux personnages : le c&ocirc;t&eacute; des plus anciens occupants (Dui Dupaan et Pabu-w&ouml;l&egrave; &quot;Petit-fils de la lune&quot;), le c&ocirc;t&eacute; des nouveaux venus accueillis comme chefs (&quot;Doigt scintillant&quot; et H&icirc;&ecirc; Bwanu &quot;Fils du soleil&quot;). On voit en effet un membre &eacute;minent du groupe des fondateurs &eacute;pouser une femme non moins prestigieuse arriv&eacute;e de l'horizon marin. L'homme de la terre, en l'occurrence de la Grande Terre, attire &agrave; lui par le son de sa fl&ucirc;te une femme de la mer, vraisemblablement originaire des Loyaut&eacute;. Au del&agrave; de la relation matrimoniale sont ici exprim&eacute;s les liens entre fondateurs d'un terroir et &eacute;trangers. Ces personnes de haut rang s'associent pour &eacute;tablir un ordre politique bien enracin&eacute; localement, mais ouvert sur l'ext&eacute;rieur. </p>
      <p class="intertitre"><a name="coquillage"></a><a href="../corpus/show_text.php?id=crdo-CAM_COQUI_SOUND&idref=crdo-CAM_COQUI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Le coquillage et les enfants</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
Nouvelle-Cal&eacute;donie,        Ty&eacute;, 1966, Sébastien Pwagu, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="intertitre">Les deux soeurs de Tècèiu dissimulent dans l'intimité de leur couche le joli coquillage (turbo) qu'elles ont découvert... Jaloux de cet intrus, Benjamin profite de l'absence de ses soeurs pour le griller et le consommer, puis, incapable de supporter les reproches qui lui sont faits, il descend vers la rivière pour s'y noyer. &quot;Si je n'ai pas le droit de toucher à vos turbos, alors consolez-vous avec eux&quot; semble dire sa complainte, tandis qu'il s'enfonce peu à peu dans l'eau de la rivière.</p>
      <p class="intertitre"><a name="oranger"></a><a href="../corpus/show_text.php?id=crdo-CAM_ORANG_SOUND&idref=crdo-CAM_ORANG"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Les enfants de l'oranger</a><br>
        Nouvelle-Cal&eacute;donie,        Ty&eacute;, 1966, Sébastien Pwagu, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint"> Le fr&egrave;re et la soeur, enfants de l'oranger de Vieux-Touho, prennent pied sur un il&ocirc;t du lagon et s'installent pour y vivre avec une vieille femme. Le chef de Vieux-Touho vient &agrave; passer au cours d'une partie de p&ecirc;che et s'&eacute;prend de la jeune fille. Il la ram&egrave;ne chez lui dans son village de Vieux-Touho. De leur union na&icirc;t un fils qui, pour une b&ecirc;tise commise en l'absence de son p&egrave;re, d&eacute;clenche la col&egrave;re de ce dernier. Les invectives pleuvent sur l'enfant mais aussi sur sa m&egrave;re (fille de l'oranger) qui se voit reprocher son inf&eacute;riorit&eacute; sociale et son origine v&eacute;g&eacute;tale. L'enfant et sa m&egrave;re regagnent leur il&ocirc;t dans le lagon mais le chef de Vieux-Touho se lance &agrave; leur poursuite...</p>
      <p class="intertitre"><a name="fruits"></a><a href="../corpus/show_text.php?id=crdo-CAM_FRUITS_SOUND&idref=crdo-CAM_FRUITS"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Les deux fruits sauvages</a> <br>
Nouvelle-Cal&eacute;donie, Kokingone, 1971, Maurice Kodèm, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Les deux filles d'Ucidaan (bord de mer de Kokingone) partent de chez elles pour se promener et explorer les environs. Elles remontent un &quot;creek&quot;, s'y installent et vivent ainsi &agrave; l'&eacute;cart de leurs fr&egrave;res et de leur famille paternelle. Alors qu'elles sont &agrave; la p&ecirc;che, elles avalent par inadvertance un fruit d'Ochrosia tomb&eacute; dans leur &eacute;puisette. L'une et l'autre con&ccedil;oivent un garcon qu'elles mettent au monde et qu'elles &eacute;l&egrave;vent. Devenus grands les deux enfants sont dot&eacute;s de frondes et de sagaies avec lesquelles ils partent chasser en direction du rivage... La suite du texte relate l'histoire de ces deux chasseurs semant la mort et la d&eacute;solation chez leurs oncles. Maudits et rejet&eacute;s par leurs m&egrave;res, ils finiront par reprendre leur forme v&eacute;g&eacute;tale premi&egrave;re dans l'arbre dont ils sont issus. </p>
      <p class="intertitre"><a name="anguille"></a><a href="../corpus/show_text.php?id=crdo-CAM_ANGUI_SOUND&idref=crdo-CAM_ANGUI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> L'anguille des Wic&egrave;</a><br>
        Nouvelle-Cal&eacute;donie,        Noum&eacute;a, 1977, Tyéu Bwaawi, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Une anguille avale un enfant laiss&eacute; dans son berceau pr&egrave;s du cours d&rsquo;eau des Wic&egrave; (lieu-dit situ&eacute; sur la rive gauche de la Tipij&eacute;, en remontant vers le Paou&eacute; et Pamal&eacute;). Incommod&eacute;e par l&rsquo;enfant, l&rsquo;anguille gagne la Tipij&eacute;, descend jusque dans l&rsquo;embouchure puis elle longe la c&ocirc;te avant de s&rsquo;engager dans la vall&eacute;e de Hiengh&egrave;ne. Elle remonte la rivi&egrave;re mais, coinc&eacute;e dans les cailloux, s&rsquo;immobilise peu apr&egrave;s Gavatch et p&eacute;rit sous les coups des jeunes gens qui l&rsquo;ont aper&ccedil;ue. A l&rsquo;int&eacute;rieur de l&rsquo;anguille, les habitants du lieu d&eacute;couvrent l&rsquo;enfant mort. Les parts de l&rsquo;anguille sont consomm&eacute;es sur place mais la m&acirc;choire est renvoy&eacute;e chez les Wic&egrave;.</p>
      </div>
</body>
</html>