<div>&nbsp;</div>
<html>
<head>
<meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
           <div class="page-header"><h1><a name="up"></a>Corpus iaai</h1></div>
     <div class="text-left"> <p class="intertitre">&nbsp;</p>
      <p class="intertitre">Fiche technique sur le <a href="../../ALC/Languages/Iaai_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false">iaai<img src="../../images/icones/info.gif" alt="a" width="15" height="15" border="0"></a></p>
      <p>&nbsp;</p>
      <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Iaai&aff=iaai" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <ul class="liste-liens">
        <li><a href="#Ciau">Ciau, la fille du chef Bahitr</a></li>
        <li><a href="#Hulup">L'origine du Kong Hulup</a></li>
        <li><a href="#Gugumelan">Les Gugumelam, deux fr&egrave;res siamois</a></li>
        <li><a href="#Oboloo">L'&eacute;cho dans le rocher Oboloo &agrave; Lekiny</a></li>
        <li><a href="#HermitCrab_CoconutCrab">Le bernard-l'hermite et le crabe de cocotier</a></li>
        </ul>
      <p>&nbsp;</p>
      <p class="intertitre"><a name="Ciau"></a><a href="../corpus/show_text.php?id=crdo-IAI_CIAU_SOUND&idref=crdo-IAI_CIAU"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Ciau, la fille du chef Bahitr</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Ouv&eacute;a, vers 1948, Wadawa Hnyigootr, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>Le th&egrave;me de ce beau texte - l'alliance et ses avatars - est commun dans la litt&eacute;rature orale kanak. Ici, Ciau, fille du chef Bahitr, entra&icirc;n&eacute;e par deux poissons &quot;watoo&quot; jusqu'&agrave; l'&icirc;lot Se&ucirc;n&ouml;-O&ucirc;deetr (dans les Pl&eacute;iades du Nord), y &eacute;pouse le Soleil. Elle a un fils, nomm&eacute; &quot;Soleil&quot;, mais, suite &agrave; une dispute avec son &eacute;poux, elle repart chez son p&egrave;re &agrave; V&euml;kiny [= Weneki en fagauvea] avec l'enfant. Le Soleil, fort m&eacute;content, au lieu d'effectuer normalement son parcours, descend chaque jour s'immobiliser juste au dessus des cocotiers de V&euml;kiny. Jour apr&egrave;s jour, le pays se dess&egrave;che et devient aride. La famine s'installe. Les gens de la tribu, en accord avec leur chef Bahitr, d&eacute;cident de rendre son fils au Soleil. <br>
        Ce texte, &eacute;crit par Wadawa Hnyigootr, fils du pasteur Ioane Hnyigootr, a &eacute;t&eacute; remis &agrave; Jean Guiart vers la fin des ann&eacute;es 40. Il a &eacute;t&eacute; reproduit et traduit par Fran&ccedil;oise Ozanne-Rivierre (<em>Mythes et contes de la Grande Terre et des &icirc;les Loyaut&eacute;</em>, SELAF, 1980, pp. 178-193). Il figure aussi en annexe du premier volume &eacute;dit&eacute; au CTRDP par Jacob et Ta&iuml; Wah&eacute;o (<em>Langue IAAI - Ouv&eacute;a. Propositions d'&eacute;criture. Hna setr hwen iaai</em>, 1987). Ce texte est lu par Ta&iuml; Waheo.</p>
      <p class="intertitre"><a name="Hulup"></a><a href="../corpus/show_text.php?id=crdo-IAI_HULUP_SOUND&idref=crdo-IAI_HULUP"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">L'origine du Kong Hulup</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Ouv&eacute;a, vers 1948, Wadawa Hnyigootr, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>Deux hommes de Canala suivent leur dieu qui fuit la montagne o&ugrave; il r&eacute;side, ravag&eacute;e par un feu de brousse. Ils d&eacute;barquent &agrave; Mouli (= Hwakai&ouml;) et, toujours &agrave; la suite du dieu, gagnent Lekiny, puis V&euml;katr mais aucun de ces endroits ne leur convient. Ils arrivent &agrave; H&acirc;ny&acirc;&ucirc; et lorsqu'un des hommes tombe au pied d'un arbre [il s'agit probablement du banyan (ib&euml;k) dont on dit qu'une des racines ressort &agrave; Canala], le tonnerre &eacute;clate, signalant que cet endroit est destin&eacute; au Kong Hulup. <br>
        Les liens anciens entre Canala et Ouv&eacute;a ont &eacute;t&eacute; largement comment&eacute;s par Jean Guiart dans <em>La structure de la chefferie en M&eacute;lan&eacute;sie du Sud</em>, 1963 (cf. p. 190 et pp. 577-581). Il a donn&eacute; p. 577 une traduction de ce texte que lui avait remis Wadawa Hnyigootr. Le texte original en langue iaai, a &eacute;t&eacute; publi&eacute; dans le volume &eacute;dit&eacute; au CTRDP par Jacob Waheo (<em>Moju bongon kau adreem. Contes et l&eacute;gendes d'Ouv&eacute;</em>a, recueil 2, 1989). Ce texte est lu par Ta&iuml; Waheo.</p>
      <p class="intertitre"><a name="Gugumelan"></a><a href="../corpus/show_text.php?id=crdo-IAI_GUGUM_SOUND&idref=crdo-IAI_GUGUM"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Les Gugumelam, deux fr&egrave;res siamois</a><a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Ouv&eacute;a, vers 1948, Tom Trongajo, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>Les Gugumelam &eacute;taient deux fr&egrave;res siamois qui avaient le pouvoir de voler comme des oiseaux et qui vivaient autrefois dans une grotte nomm&eacute;e Beetr. Ils avaient la d&eacute;testable habitude de tuer et de mettre au four les individus qui se trouvaient dans des groupes de personnes en nombre impair. Seuls, &eacute;taient &eacute;pargn&eacute;s, les gens de leur clan, c'est-&agrave;-dire les sujets de Ihili et Draume. Lass&eacute;s de vivre dans la terreur, les sujets iaai implor&egrave;rent Draume de leur permettre de tuer les deux fr&egrave;res siamois, ce qui leur fut accord&eacute;. Le jour de leur ex&eacute;cution, les Gugumelam laiss&egrave;rent le message suivant : ne plus manger de cocos doubles, ni aucun fruit jumel&eacute; en souvenir d'eux. <br>
        Ce texte a &eacute;t&eacute; &eacute;crit par Tom Trongajo, &agrave; la fin des ann&eacute;es 40. Jean Guiart le mentionne dans son ouvrage <em>La chefferie en M&eacute;lan&eacute;sie du Sud</em>, 1963, p.575. Une version avec traduction et mot &agrave; mot a &eacute;t&eacute; publi&eacute;e par Fran&ccedil;oise Ozanne-Rivierre (<em>Mythes et contes de la Grande Terre et des &icirc;les Loyaut&eacute;</em>, SELAF, 1980, pp. 194-201). Ce texte est lu par Ta&iuml; Waheo. Une autre version de l'histoire des fr&egrave;res siamois, transcrite en iaai et traduite en fran&ccedil;ais par Pierre Samuel et Isma&euml;l Saidhine, existe dans le document <em>Contes et l&eacute;gendes d'Ouv&eacute;a</em> (texte 5) &eacute;labor&eacute; en 1981 par des enfants de quatri&egrave;me du coll&egrave;ge Guillaume Douarre.</p>
      <p class="intertitre"><a name="Oboloo"></a><a href="../corpus/show_text.php?id=crdo-IAI_OBOLO_SOUND&idref=crdo-IAI_OBOLO"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">L'&eacute;cho dans le rocher Oboloo &agrave; Lekiny</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Ouv&eacute;a, vers 1948, Joël Mauu, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>Pour avoir viol&eacute; un interdit (consommer de la mur&egrave;ne), des hommes seront recouverts par le rocher Oboloo, dans les falaises de Lekiny. Aujourd'hui, lorsqu'on appelle &agrave; cet endroit, l'&eacute;cho vous r&eacute;pond. <br>
        Ce texte a &eacute;t&eacute; &eacute;crit par Mauu, Jo&euml;l vers la fin des ann&eacute;es 40. Il a &eacute;t&eacute; publi&eacute; et traduit par F. Ozanne-Rivierre dans <em>Les langues M&eacute;lan&eacute;siennes de Nouvelle-Cal&eacute;donie</em>, Collection Eveil 13, Noum&eacute;a, D.E.C., 1979, p.93-94. Il figure aussi dans le volume &eacute;dit&eacute; par Jacob Waheo au CTRDP - Langues Vernaculaires en 1989 (<em>Moju bongon kau adreem. Contes et l&eacute;gendes d'Ouv&eacute;a</em>, recueil 2, p. 43). Ce texte est lu par Ta&iuml; Waheo.</p>
      <p class="intertitre"><a name="HermitCrab_CoconutCrab" id="HermitCrab_CoconutCrab"></a><a href="../corpus/show_text.php?id=crdo-IAI_OVETH_SOUND&idref=crdo-IAI_OVETH"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le bernard-l'hermite et le crabe de cocotier</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Noum&eacute;a, vers 1948, Wakuba Ianu, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>    Cette petite fable, tr&egrave;s classique &agrave; Ouv&eacute;a, explique pourquoi le bernard-l'hermite s'habille toujours avec les v&ecirc;tements des autres et pourquoi le crabe de cocotier, honteux de montrer sa nudit&eacute;, se manifeste surtout la nuit. La morale de l'histoire (dans cette version du moins !) est qu'il faut ... respecter les femmes. <br>
        Ce texte a &eacute;t&eacute; racont&eacute; &agrave; Ta&iuml; Waheo par son grand-p&egrave;re Wakuba Ianu. Il a &eacute;t&eacute; publi&eacute; dans le recueil <em>Langue Iaai Ouvea, propositions d'&eacute;criture</em> ( p.100-101), publi&eacute; en 1987 au CTRDP-Langues Vernaculaires (Ta&iuml; Waheo et Jacob Waheo eds).</p>
        </div>
</body>
</html>