 <div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
            <div class="page-header"><h1><a name="up"></a>Iaai Corpus </h1></div>
            <div class="text-left">
      <p class="intertitre">&nbsp;</p>
      <p class="intertitre"><a href="../../ALC/Languages/Iaai_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false"><img src="../../images/icones/info.gif" alt="a" width="15" height="15" border="0">Iaai</a>: a brief note </p>
      <p>&nbsp;</p>
      <h4 align="left">Resources :</h4>
      <p class="intertitre">
      <img src="../../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc_en.php?lg=Iaai&aff=iaai" target="_blank"> All available resources here
      </a></p>
      <p class="intertitre">&nbsp;</p>
      <ul class="liste-liens">
        <li><a href="#Ciau">Ciau, the Ceadman Bahitr's Daughter</a></li>
        <li><a href="#Hulup">The Origin of the Kong Hulup</a></li>
        <li><a href="#Gugumelan">The Siamese-Twin Brothers Gugumelan</a></li>
        <li><a href="#Oboloo">The Echo in the Oboloo Rock at Lekiny</a></li>
        <li><a href="#HermitCrab_CoconutCrab">The Hermit-Crab and the Coconut Crab</a></li>
      </ul>
      <p>&nbsp;</p>
      <p class="intertitre"><a name="Ciau"></a><a href="../corpus/show_text_en.php?id=crdo-IAI_CIAU_SOUND&idref=crdo-IAI_CIAU"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Ciau, the Headman Bahitr's Daughter</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Uvea, c.1948, Wadawa Hnyigootr, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>The theme of this lovely text –alliances and what comes of them– is common in Kanak oral literature. Here, Ciau, the headman Bahitr&rsquo;s daughter, is pulled by two &ldquo;watoo&rdquo; fish all the way to the Se&ucirc;n&ouml;-O&ucirc;deetr islet (in the northern Pleiades), to marry the Sun. She has a son, named &ldquo;Sun&rdquo;, but, following an argument with her husband, she goes back to live with her father in V&euml;kiny [= Weneki in Fagauvea] with her child. The Sun, very angry, instead of carrying out his usual course, descends each day and stops just above the V&euml;kiny coconut trees. This happens day after day until the countryside is dry and parched. Famine begins. The tribe&rsquo;s members, in agreement with their headman Bahitr, decide to give the Sun back his son. This text, written by Wadawa Hnyigootr, son of Father Ioane Hnyigootr, was given to Jean Guiart towards the late 1940s. It was copied and translated by Fran&ccedil;oise Ozanne-Rivierre (<em>Mythes et contes de la Grande Terre et des &icirc;les Loyaut&eacute;</em>, SELAF, 1980, pp. 178-193). It is also to be found in the annex to the first volume edited at the CTRDP by Jacob and Ta&iuml; Wah&eacute;o (<em>Langue IAAI - Ouv&eacute;a. Propositions d'&eacute;criture. Hna setr hwen iaai</em>, 1987). This reading is by Ta&iuml; Waheo.</p>
      <p class="intertitre"><a name="Hulup"></a><a href="../corpus/show_text_en.php?id=crdo-IAI_HULUP_SOUND&idref=crdo-IAI_HULUP"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Origin of the Kong Hulup </a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Ouv&eacute;a, c.1948, Wadawa Hnyigootr, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>Two men from Canala follow their god fleeing the mountain where he resided, destroyed by a brush fire. They disembark at Mouli (=Hwakai&ouml;) and, still in the wake of their god, they come to Lakiny, then V&euml;katr, but none of these places suit them. They then come to H&acirc;ny&acirc;&ucirc; and, as one of the men falls at the foot of a tree [probably the banyan (ib&euml;k) of which it is said that one of its roots comes out at Canala], there is a roll of thunder, signifying that the spot is destined for Kong Hulup. The ancient ties between Canala and Uvea are abundantly commented by Jean Guiart in <em>La structure de la chefferie en M&eacute;lan&eacute;sie du Sud</em>, 1963 (<em>cf</em>. p. 190 and pp. 577-581). Page 577 he gives a translation of this text which had been given to him by Wadawa Hnyigootr. The original text in the Iaai language was published in the volume edited at the CTRDP by Jacob Waheo (<em>Moju bongon kau adreem. Contes et l&eacute;gendes d'Ouv&eacute;</em>a, recueil 2, 1989). This reading is by Ta&iuml; Waheo.</p>
      <p class="intertitre"><a name="Gugumelan"></a><a href="../corpus/show_text_en.php?id=crdo-IAI_GUGUM_SOUND&idref=crdo-IAI_GUGUM"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Siamese-Twin Brothers Gugumelam</a> <a href="../corpus/show_text.php?id=crdo-IAI_GUGUM_SOUND" target="_blank"> </a><a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Uvea, c.1948, Tom Trongajo, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>The Gugumelam brothers were Siamese twins who had the ability to fly like birds and who lived in a cave called Beetr. They had the despicable habit of killing and roasting those who appeared in groups of odd numbers of people. Only people from their own clan were spared, which is to say the subjects of Ihili and Draume. Tired of living in terror, the Iaai subjects implored Draume to let them kill the Siamese twins. Permission was granted. The day of their execution, the Gugumelam brothers left the following message: abstain from eating double coconuts or any other paired fruit in memory of us. This text was written by Tom Trongajo, in the late 1940s. Jean Guiart mentions it in his book <em>La chefferie en M&eacute;lan&eacute;sie du Sud</em>, 1963, p.575. A version with a word by word translation is published by Fran&ccedil;oise Ozanne-Rivierre (<em>Mythes et contes de la Grande Terre et des &icirc;les Loyaut&eacute;</em>, SELAF, 1980, pp. 194-201). This reading is by Ta&iuml; Waheo. Another version of the Siamese brothers, transcribed in Iaai and translated into French by Pierre Samuel and Isma&euml;l Saidhine can be found in the <em>Contes et l&eacute;gendes d'Ouv&eacute;a</em> document (text 5) put together in 1981 by fifth graders from the Coll&egrave;ge Guillaume Douarre..</p>
      <p class="intertitre"><a name="Oboloo"></a><a href="../corpus/show_text_en.php?id=crdo-IAI_OBOLO_SOUND&idref=crdo-IAI_OBOLO"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Echo in the Oboloo Rock at Lekiny</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Uvea, c.1948, Joël Mauu, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>For having transgressed a taboo (eating moray eel), a group of men is covered by the Oboloo rock, in the Lekiny cliffs. Today, when one calls in this spot, an echo answers. This text was written by Jo&euml;l Mauu in the late 1940s. It was translated and published by Fran&ccedil;oise Ozanne-Rivierre in <em>Les langues M&eacute;lan&eacute;siennes de Nouvelle-Cal&eacute;donie</em>, Collection Eveil 13, Noum&eacute;a, D.E.C., 1979, p.93-94. It also figures in the work edited by Jacob Waheo at the CTRDP - Langues Vernaculaires en 1989 (<em>Moju bongon kau adreem. Contes et l&eacute;gendes d'Ouv&eacute;a</em>, recueil 2, p. 43). This reading is by Ta&iuml; Waheo.</p>
      <p class="intertitre"><a name="HermitCrab_CoconutCrab" id="HermitCrab_CoconutCrab"></a><a href="../corpus/show_text_en.php?id=crdo-IAI_OVETH_SOUND&idref=crdo-IAI_OVETH"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Hermit-Crab and the Coconut Crab </a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Noum&eacute;a, c.1948, Wakuba Ianu, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>This short fable, a great classic in Uvea, explains why the hermit crab always wears the clothes of others and why the coconut crab, ashamed of his nakedness, mostly only comes out at night. The moral of the story (at least in this version!) is that one must... respect women. This text was told to Ta&iuml; Waheo by his grandfather Wakuba Ianu. It was published in the collection <em>Langue Iaai Ouvea, propositions d'&eacute;criture</em> (p.100-101) in 1987 by the CTRDP-Langues Vernaculaires (Ta&iuml; Waheo et Jacob Waheo eds).</p>
      </div>
</body>
</html>