<div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
           <div class="page-header"><h1><a name="up"></a>Corpus drehu</h1></div>
       <div class="text-left"><p class="intertitre">&nbsp;</p>
      <p class="intertitre">Fiche technique sur le <a href="../../ALC/Languages/Drehu_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false">drehu<img src="../../images/icones/info.gif" alt="a" width="15" height="15" border="0"></a></p>
      <p class="intertitre">&nbsp;</p>
      <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Drehu&aff=drehu" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <p class="intertitre"><a href="../corpus/show_text.php?id=crdo-DHV_MU_SOUND&idref=crdo-DHV_MU"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Arriv&eacute;e de Tongiens &agrave; Mu (Lifou, Iles Loyaut&eacute;)<br>
  </a>Nouvelle-Cal&eacute;donie, Mu (Lifou), 1997, Wanum Maka, <a href="../../membres/moyse.htm">Claire Moyse-Faurie </a></p>
      <p>Plusieurs r&eacute;cits relatent l'arriv&eacute;e de migrations polyn&eacute;siennes en provenance des &icirc;les Tonga, Samoa, Wallis ou Futuna, vraisemblablement entre le XVIe et le tout d&eacute;but du XIXe si&egrave;cle. De telles migrations ont sans doute exist&eacute; aussi &agrave; des dates plus anciennes. Ce r&eacute;cit relate l'arriv&eacute;e d'une migration tongienne qui se serait fix&eacute;e &agrave; Mu (Lifou) apr&egrave;s une br&egrave;ve halte &agrave; Walpole et un s&eacute;jour de plusieurs ann&eacute;es &agrave; l'&icirc;le des Pins. M. J. Dubois, dans Kw&egrave;nyii, l'&icirc;le des Pins aux temps anciens, SEHNC, &eacute;voque le naufrage, vers 1810, d'un bateau ayant &agrave; son bord des matelots tongiens, &agrave; Wania (not&eacute;e Ouigna par le P&egrave;re Lambert), pr&egrave;s de la baie de la Corbeille &agrave; l'&icirc;le des Pins. Auparavant, vers 1770, du temps du chef K&euml;&euml;wa, une pirogue venue de Tonga se serait d&eacute;j&agrave; bris&eacute;e dans la baie d'Ayogi. Selon Glaumont (Ethnog&eacute;nie des insulaires de Kuni&eacute; (&icirc;les des Pins), <em>Revue d'Ethnographie</em>, Paris, 1887), dix hommes et six femmes venus de Tonga se seraient &eacute;chou&eacute;s &agrave; l'&icirc;le des Pins, apr&egrave;s &ecirc;tre pass&eacute;s par Walpole. Quelques ann&eacute;es plus tard, ces Tongiens se seraient effectivement install&eacute;s &agrave; Lifou, dans la baie de Mu, o&ugrave; leurs descendants vivent encore, et portent le nom de angetre Tonga &quot;gens de Tonga&quot;. La narratrice de ce r&eacute;cit est l'&eacute;pouse de l'un de ces descendants, d&eacute;c&eacute;d&eacute; il y a quelques ann&eacute;es. Elle attribue &agrave; un d&eacute;nomm&eacute; Taufa la reconnaissance de l'&eacute;vang&eacute;liste Fao &agrave; son arriv&eacute;e &agrave; Ahmelewedr, faisant, selon J. Guiart, une confusion avec un personnage du m&ecirc;me nom qui aurait accueilli &agrave; Mar&eacute;, en 1841, le navire missionnaire de la L.M.S., le Camden. A juste titre, Guiart (<em>Structure de la chefferie en M&eacute;lan&eacute;sie du Sud</em>, 1963, pp. 205-209) rel&egrave;ve la similitude des raisons avanc&eacute;es pour le d&eacute;part des Tongiens s'&eacute;tant install&eacute;s &agrave; Lifou, et pour celui des Wallisiens parvenus &agrave; Ouv&eacute;a : suite &agrave; un accident, ou &agrave; une guerre, le fils d'un chef est bless&eacute; ou tu&eacute;. Par peur de repr&eacute;sailles, les coupables s'enfuient en pirogue. Au-del&agrave; d'un incident mettant en cause le fils d'un chef, ces migrations pouvaient &ecirc;tre dues &agrave; un ensemble de causes plus complexes : manque de terres, dissensions entre chefferies, recherche de nouvelles relations matrimoniales.</p>
      </div>
</body>
</html>