<div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
            <div class="page-header"><h1><a name="up"></a>West Uvean Corpus </h1></div>
            <div class="text-left">
      <p class="intertitre">&nbsp;</p>
      <p class="intertitre"><a href="../../ALC/Languages/Fagauvea_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false"><img src="../../images/icones/info.gif" alt="a" width="15" height="15" border="0">West Uvean</a>: a brief note </p>
      <p>&nbsp;</p>
       <h4 align="left">Resources :</h4>
      <p class="intertitre">
      <img src="../../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc_en.php?lg=Fagauvea&aff=fagauvea" target="_blank"> All available resources here
      </a></p>
      <p class="intertitre">&nbsp;</p>
      <ul class="liste-liens">
        <li><a href="#Nemejie">Chief Drumai's Wife and the Witch Nemejie</a></li>
        <li><a href="#Heo">The Two Boys from Heo who Were Turned into Rocks</a></li>
        <li><a href="#Takeji">The Takeji Rock</a></li>
        <li><a href="#rail_swamphen">The Rail and the Swamp Hen</a></li>
        <li><a href="#chiefdoms">The Origin of the Polynesian Chiefdoms in Uvea (Loyalty Islands)</a></li>
        <li><a href="#KingfisherBuzzard">The Kingfisher and the Buzzard </a></li>
        <li><a href="#Ohnyat">The Wind Rock at Ohnyat</a></li>
        <li><a href="#Aneua">The Waterhole at Aneua</a></li>
        <li><a href="#Motutapu">The Legend of the Woman from Motutapu</a></li>
        <li><a href="#Bebea">The Story of Bebea</a></li>
        <li><a href="#Muli">Atunai Arrives at Muli</a></li>
        <li><a href="#Drumai">The Origin of the Name &quot;Drumai&quot;</a></li>
        <li><a href="#HermitCrab_CoconutCrab">The Two Hermit Crabs and the Coconut Crab</a></li>
      </ul>
      <p class="intertitre"><a name="Nemejie"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_LOGOTI_SOUND&idref=crdo-UVE_LOGOTI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Chief Drumai's Wife and the Witch Nemejie</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Mouli (Uvea), 1971, Fereol Bali, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>The theme of witches who drown the pregnant wives of chiefs in order to take their place is a recurrent one in certain linguistic areas of the Grande Terre, and especially in the C&egrave;muh&icirc; area where the witch bears the name &ldquo;Awii-d&egrave;l&egrave;-apulip&rdquo; (lit. &ldquo;she who eats people&rsquo;s waste&rdquo;), cf. Rivierre, Dictionnaire c&egrave;muh&icirc;-fran&ccedil;ais, Paris, SELAF, 1994. In this text in Fagauvea, the witch is called Nemejie and her victim is chief Drumai of Mouli&rsquo;s wife. Once her evil deed accomplished, the witch swallows everything she can lay her hands on, cooking pots, plates, lizards, etc., to make herself look pregnant. In the meantime, the drowned wife drifted to an islet where she was fished out by an old woman chief, Logoti. She then gave birth to twins, named Wanima and Waneume. One day when the boys were paddling in the islets of the southern Pleiades, they were captured by some of Drumai&rsquo;s subjects. Destined to be roasted, they were luckily recognized by their father, and the witch, discovered, was executed. Since then, the eldest in the chiefdom is called Wanima and his younger brother is called Waneume. Another version of this text, written and translated into Fagauvea by Herv&eacute; Alosio&rsquo;s mother, can be found in the tome Contes et L&eacute;gendes d&rsquo;Ouv&eacute;a (&ldquo;O Doumai&rdquo;, text 8), confectioned in 1981 by 6th graders at the Guillaume Douarre school. In the same document, there is also a version, quite parallel, but this time concerning the Beka chiefdom in the north of Uvea. This text, entitled &ldquo;Les deux garcons d&rsquo;Ougn&eacute; {Unyee]&rdquo; (text 12) was recorded in T&eacute;outa in 1981 from P&eacute;lagie Gnida. It was transcribed in Fagauvea by Laurentine and Agn&egrave;s Laouniou, and translated into French by Laurentine.</p>
      <p class="intertitre"><a name="Heo"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_TALIAFI_SOUND&idref=crdo-UVE_TALIAFI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Two Boys from Heo who Were Turned into Rocks</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, H&eacute;o (Uvea), 1997, Noela Tulangi, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Heo (Beautemps-Beaupr&eacute;), Motutapu, Motuone and Bunaaca make up part of a small currently uninhabited archipelago to the north west of the northern Pleiades, the latter, along with the southern Pleiades, constituting the Uvea lagoon. In Bunaaca lived a woman. (Who might perhaps be Logoti, the goddess of Heo who, being mistreated, fled to Motutapu; indeed, Bunaaca island is sometimes described as Heo&rsquo;s invisible double). One day, this woman sent two young boys to fetch wood on Heo, so as to make a fire to burn up all the spider webs invading her island. The youths did not respect the taboo - not to speak to Heo&rsquo;s inhabitants - and were turned into stone, becoming the two rocks which one may see today off the shores of Heo.</p>
      <p class="intertitre"><a name="Takeji"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_FATU_SOUND&idref=crdo-UVE_FATU"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Takeji Rock</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Tak&eacute;ji (Uvea), 1997, Marthe Sivitango, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Located inside the walls of the Nekelo chiefdom in Takeji, this sacred stone is in a way the symbol of respect towards the established social order and the behavior subjects must have towards the chiefdom. Any individual disobedience entails grave consequences for the whole society.</p>
      <p class="intertitre"><a name="rail_swamphen"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_KALAE_SOUND&idref=crdo-UVE_KALAE"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Rail and the Swamp Hen</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, H&eacute;o (Uvea), 1997, Valentine Ouckeiwen, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This &ldquo;animal story&rdquo; illustrates how two New Caledonian birds, the rail and the swamp hen, find their means of subsistence.</p>
      <p class="intertitre"><a name="chiefdoms"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_CHEF_SOUND&idref=crdo-UVE_CHEF"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Origin of the Polynesian Chiefdoms in Uvea (Loyalty Islands)</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, W&eacute;n&eacute;ki (Uvea), 1997, Amédée Nahyet, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Several Polynesian migrations to Uvea, mostly, according to the oral traditions, from Wallis (whose name in Wallisian is precisely Uvea), most probably took place between the 16th and 18th centuries. The pretext for the voyage given in this account is a desire for adventure, for discovering new lands. In other versions, the reasons invoked are similar to those which explain the Tongan migration to Lifou: the son of a Wallis chief is wounded or killed while building canoes, and the guilty ones flee to avoid being punished. The prediction which is to allow them to recognize the desired island (a mullet fish jumping over a mangrove leaf) and the departing message from the spirit of the old Wallisian woman are often mentioned in Uvea. In the north of Uvea, the Polynesians were welcomed by the grand Iaai chief Bazit, who wanted to use them as allies against his traditional rivals. The names of these Polynesian chiefs are said to have been modified after their settlement on Uvea: Kaukelo, Peka and Atunai are said to have become, respectively, Nekelo, Beka and Drumai. The descendents of this migration speak Fagauvea, a Polynesian language, which was enriched through contact with Iaai (phonology and vocabulary).</p>
      <p class="intertitre"><a name="KingfisherBuzzard"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_WAJIJI_SOUND&idref=crdo-UVE_WAJIJI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Kingfisher and the Buzzard</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, W&eacute;n&eacute;ki (Uvea), 1997, Amédé Nayet, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This &ldquo;animal story&rdquo;, of an allegorical nature, symbolizes workload sharing on the plantations. The kingfisher, with his gaudy plumage, shows himself during the day and takes care of preparing the small mounds, or &ldquo;mole hills&rdquo; where coco yam tubers are buried, also called &ldquo;walei&rdquo;. The buzzard, whose plumage is dull and dark, works at night attaching the stalks of the young yam sprouts before announcing the break of day. The wild duck, a black and white forest bird, supervises the work of the other two while predicting fair or foul weather.</p>
      <p class="intertitre"><a name="Ohnyat"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_MATANGI_SOUND&idref=crdo-UVE_MATANGI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Wind Rock at Ohnyat</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, W&eacute;n&eacute;ki (Uvea), 1997, Amédé Nayet, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This account tells of the continuing alliances between Uvea and Lifou islands, through the intermediary of the Hnadruao clan on Ohnyat, who originated from Unatr&euml; village on Lifou, to which the Drehudrohu family and their wind master also belong. One calls upon the latter when one wishes for favorable winds to sail to Lifou island, or, more prosaically, to get rid of mosquitoes which swarm in droves when the weather is hot and humid. It is also said that there is a reef between Uvea and Lifou where people from Ohnyat who want to go to Lifou, where they originally came from, carry out certain ritual gestures. </p>
      <p class="intertitre"><a name="Aneua"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_ANEUA_SOUND&idref=crdo-UVE_ANEUA"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Waterhole at Aneua</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, W&eacute;n&eacute;ki (Uvea), 1997, Jean-Marie Ngavit,, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This story, presented as being true, tells of the tragic death of a young man who, driven by his pride, wanted to attract the attention of his friends by counting too much on his physical strength.</p>
      <p class="intertitre"><a name="Motutapu"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_MOTUTAPU_SOUND&idref=crdo-UVE_MOTUTAPU"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Legend of the Woman from Motutapu</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Mouli (Uvea), 1997, Paul Mitcham , <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Heo (Beautemps-Beaupr&eacute;), Motutapu, Motuone and Bunaaca make up part of a small archipelago, uninhabited today, located to the north west of the northern Pleiades, the latter constituting, along with the southern Pleiades, the Uvea lagoon. The goddess Logoti is said to have fled Heo because of the ill treatment she received at the hands of the dirty and noisy inhabitants there, to seek refuge in Motutapu. Because of this, women and chiefs can no longer go to Motutapu.</p>
      <p class="intertitre"><a name="Bebea"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_BEBEA_SOUND&idref=crdo-UVE_BEBEA"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Story of Bebea</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Mouli (Uvea), 1997, Lazare Wegué, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>A rock with a rounded shape is situated on the Dengala islet (sometimes called the &ldquo;High islet&rdquo;) to the east of Angen island, in the northern Pleiades archipelago. This rock is in fact a young man, called Bebea or Ameti. His curiosity aroused by noises coming from the &ldquo;big island&rdquo; (Heo or Angen?), the young man had obtained permission from his grandmother to go there: in reality, it was the land of the dead and, even though he was entirely covered with crab juice, the young man was unmasked as a stranger during the dance of the dead. His excursion to the land of the dead earned him a petrified return to his original islet</p>
      <p class="intertitre"><a name="Muli"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_ATUNAI_SOUND&idref=crdo-UVE_ATUNAI"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Atunai Arrives at Muli </a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Noum&eacute;a, Vall&eacute;e du Tir, 1997, Marie-Josèphe Drumai, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This text offers an explanation for the Polynesian migration to Uvea (Loyalty Islands), mostly, according to the oral traditions, from Wallis/Uvea, which most probably took place between the 16th and 18th centuries. The pretext given in this account is an accident which is said to have befallen a chief&rsquo;s son in Wallis during canoe construction work, the guilty party then fleeing to avoid repercussions. The farewell message of an old Wallisian woman explaining to the fleeing party how to recognize their final destination &ndash; the island with a mullet fish jumping over a mangrove leaf &ndash; is found in identical form in several other versions. However, the story by Drumai, Marie-Jos&egrave;phe is original in that it associates a different tree leaf and fish for each of the stopping points of the three Wallisian chiefs Nekelo (formerly Kaukelo), Peka (Beka) and Atunai, later to become Drumai. In Wallis itself, oral traditions have conserved the name of the old woman &ndash; Sogotautau, who is said to have risen from the tomb to deliver the message to the fleeing party as they were leaving the island by the Avatolu pass &ndash; and the name of their canoe, Ifilaupakola. Frimigacci (Un poisson nomm&eacute; Uvea : &eacute;l&eacute;ments d'ethnohistoire de Wallis, Noum&eacute;a, CTRDP) dates the canoe&rsquo;s departure at around 1750. The author of this account is the daughter of the former chief of Mouli, Carolo Drumai, who, not having any sons, passed the chiefdom on to his nephew Pierre Drumai.</p>
      <p class="intertitre"><a name="Drumai"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_TAFOLAA_SOUND&idref=crdo-UVE_TAFOLAA"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Origin of the Name &quot;Drumai&quot;</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Noum&eacute;a, Vall&eacute;e du Tir, 1997, Marie-Josèphe Drumai, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This myth tells the story of an alliance between a woman from the Grande Terre (either from Petit-Couli or from Kouaoua, depending on the version) and the Atunia chiefdom in Mouli, of Wallisian origin. The story recounts that the woman, who was pregnant, arrived in the belly of a whale, which she caused to be beached by tickling its insides with a kuku shell, a shell usually used to peel roots, which women always keep with them. The woman&rsquo;s child is said to have become the chief of Mouli, under the name of Drumai. J. Guiart (1963, Structure de la chefferie en M&eacute;lan&eacute;sie du sud, Institut d'ethnologie du Mus&eacute;e de l'Homme) presents a different version of this story, collected in the Poindimi&eacute; region: the Nebay clan of the Grande Terre is said to originally be Dumay, whose ancestor was swallowed along with his mother, wife of the chief Dumay, by a shark while she was crossing the Kouaoua river.</p>
      <p class="intertitre"><a name="HermitCrab_CoconutCrab"></a><a href="../corpus/show_text_en.php?id=crdo-UVE_MOCIKA_SOUND&idref=crdo-UVE_MOCIKA"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Two Hermit Crabs and the Coconut Crab</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        New Caledonia, Ohnyat (Uvea), 1997, Félicien Idakote, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>This story recounts why the hermit crab hides in the empty shells it happens upon, whereas the coconut crab is not ashamed to walk around naked.</p>
      </div>
</body>
</html>