 <div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
           <div class="page-header"><h1><a name="up"></a>Corpus fagauvea<em> </em></h1></div>
       <div class="text-left"><p class="intertitre">&nbsp;</p>
      <p class="intertitre">Fiche technique sur le <a href="../../ALC/Languages/Fagauvea_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false">fagauvea<img src="../images/icones/info.gif" alt="a" width="15" height="15" border="0"></a></p>
      <p>&nbsp;</p>
       <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Fagauvea&aff=fagauvea" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <p>Les textes ont &eacute;t&eacute; recueillis par F. Ozanne-Rivierre et C. Moyse-Faurie. </p>
      <ul class="liste-liens">
        <li><a href="#Nemejie">L'&eacute;pouse du chef Drumai et la sorci&egrave;re Nemejie</a></li>
        <li><a href="#Heo">Les deux gar&ccedil;ons chang&eacute;s en pierres &agrave; Heo</a></li>
        <li><a href="#Takeji">La pierre de Takeji</a></li>
        <li><a href="#rail_swamphen">Le r&acirc;le et de la poule sultane</a></li>
        <li><a href="#chiefdoms">Origine des chefferies polyn&eacute;siennes d'Ouv&eacute;a (Iles Loyaut&eacute;)</a></li>
        <li><a href="#KingfisherBuzzard">Le martin-p&ecirc;cheur et la buse</a></li>
        <li><a href="#Ohnyat">La pierre du vent &agrave; Ohnyat</a></li>
        <li><a href="#Aneua">Le trou d'eau d'Aneua</a></li>
        <li><a href="#Motutapu">L&eacute;gende de la femme de Motutapu</a></li>
        <li><a href="#Bebea">Histoire de Bebea</a></li>
        <li><a href="#Muli">L'arriv&eacute;e d'Atunai &agrave; Mouli</a></li>
        <li><a href="#Drumai">L'origine du nom &quot;Drumai&quot;</a></li>
        <li><a href="#HermitCrab_CoconutCrab">Les deux bernard-l'hermite et le crabe de cocotier</a></li>
        </ul>
      <p class="intertitre"><a name="Nemejie"></a><a href="../corpus/show_text.php?id=cocoon-5c583557-41b5-3858-99d7-7aa24e1801e1&idref=cocoon-85afd245-ed84-33ea-bb51-7fdbd6b4ff2e"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">L'&eacute;pouse du chef Drumai et la sorci&egrave;re Nemejie</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
Nouvelle-Cal&eacute;donie, Mouli (Ouv&eacute;a), 1971, Fereol Bali, <a href="../../membres/ozanne.htm">Fran&ccedil;oise Ozanne-Rivierre</a></p>
      <p>Le th&egrave;me des sorci&egrave;res qui noient les femmes de chef enceintes pour prendre leur place est r&eacute;current dans certaines aires linguistiques de la Grande Terre et, notamment, dans l'aire c&egrave;muh&icirc; o&ugrave; cette sorci&egrave;re porte le nom de &quot;Awii-d&egrave;l&egrave;-apulip&quot; (litt. &quot;celle qui mange les d&eacute;chets des gens&quot;), <em>cf</em>. Rivierre, <em>Dictionnaire c&egrave;muh&icirc;-fran&ccedil;ais</em>, Paris, SELAF, 1994. Dans ce texte en fagauvea, la sorci&egrave;re se nomme Nemejie et sa victime est l'&eacute;pouse du chef Drumai de Mouli. Une fois son forfait accompli, cette sorci&egrave;re avale tout ce qui lui tombe sous la main, marmites, assiettes, l&eacute;zards, etc., pour faire croire qu'elle est enceinte. Pendant ce temps, l'&eacute;pouse noy&eacute;e d&eacute;rive jusqu'&agrave; un &icirc;lot o&ugrave; elle est recueillie par une vieille femme chef, Logoti. Elle accouchera de deux jumeaux nomm&eacute;s Wanima et Waneume. Un jour o&ugrave; les deux gar&ccedil;ons naviguent dans les &icirc;lots des Pl&eacute;ïades du sud, ils sont captur&eacute;s par les sujets de Drumai. Destin&eacute;s &agrave; &ecirc;tre mis au four, ils seront, heureusement, reconnus par leur p&egrave;re et la sorci&egrave;re, d&eacute;masqu&eacute;e, sera ex&eacute;cut&eacute;e. C'est depuis ce temps-l&agrave; que l'a&icirc;n&eacute; de la chefferie Drumai porte le nom de Wanima et son cadet, celui de Waneume. Une version de ce texte, &eacute;crite et traduite en fagauvea par la m&egrave;re d'Herv&eacute; Alosio, figure dans le recueil <em>Contes et L&eacute;gendes d'Ouv&eacute;a</em> (&quot;O Doumai&quot;, texte 8), &eacute;labor&eacute; en 1981 par des enfants de quatri&egrave;me du coll&egrave;ge Guillaume Douarre. Dans ce m&ecirc;me document, on trouve aussi une version, assez parall&egrave;le, concernant cette fois la chefferie beka au nord d'Ouv&eacute;a. Ce texte, intitul&eacute; &quot;Les deux gar&ccedil;ons d'Ougn&eacute; [Unyee]&quot; (texte 12), a &eacute;t&eacute; recueilli &agrave; T&eacute;outa en 1981 aupr&egrave;s de P&eacute;lagie Gnida. Il a &eacute;t&eacute; transcrit en fagauvea par Laurentine et Agn&egrave;s Laouniou, et traduit en fran&ccedil;ais par Laurentine.</p>
      <p class="intertitre"><a name="Heo"></a><a href="../corpus/show_text.php?id=cocoon-9506a78a-f468-33b6-a026-2bc8f0aeccb1&idref=cocoon-547cb022-7c79-33d3-8a2a-a5ca7e35da9f"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Les deux gar&ccedil;ons chang&eacute;s en pierres &agrave; Heo</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
Nouvelle-Cal&eacute;donie, H&eacute;o (Ouv&eacute;a), 1997, Noela Tulangi, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Heo (Beautemps-Beaupr&eacute;), Motutapu, Motuone et Bunaaca font partie d'un petit archipel, actuellement inhabit&eacute;, situ&eacute; au nord-ouest des Pl&eacute;&iuml;ades du nord, ces derni&egrave;res fermant, avec les Pl&eacute;&iuml;ades du sud, le lagon d'Ouv&eacute;a. A Bunaaca r&eacute;sidait une femme. (Il s'agit peut-&ecirc;tre de Logoti, d&eacute;esse de Heo qui, maltrait&eacute;e, se serait r&eacute;fugier &agrave; Motutapu ; en effet, l'&icirc;le de Bunaaca est parfois d&eacute;crite comme &eacute;tant le double invisible de Heo). Un jour, cette femme envoya deux jeunes gar&ccedil;ons ramasser du bois &agrave; Heo, afin de pouvoir faire du feu et griller les toiles d'araign&eacute;e qui envahissaient son &icirc;le. Les jeunes ne respect&egrave;rent pas l'interdit - ils ne devaient pas parler aux habitants de Heo - et furent p&eacute;trifi&eacute;s, devenant les deux rochers que l'on peut voir d&eacute;sormais au large de Heo.</p>
      <p class="intertitre"><a name="Takeji"></a><a href="../corpus/show_text.php?id=cocoon-e0702d65-d496-3d59-a68b-863247425a35&idref=cocoon-9f518208-ef6a-328b-809a-4ed4b239856b"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">La pierre de Takeji</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Tak&eacute;ji (Ouv&eacute;a), 1997, Marthe Sivitango, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Situ&eacute;e &agrave; l'int&eacute;rieur de l'enclos de la chefferie Nekelo &agrave; Takeji, cette pierre sacr&eacute;e est en quelque sorte le symbole du respect de l'ordre social et du bon comportement que doivent avoir les sujets vis-&agrave;-vis de la chefferie. Tout manquement individuel &agrave; cet ordre sera lourd de cons&eacute;quences pour la collectivit&eacute; toute enti&egrave;re.</p>
      <p class="intertitre"><a name="rail_swamphen"></a><a href="../corpus/show_text.php?id=cocoon-9363c7b7-3548-3825-ae6d-15c64ba5dc67&idref=cocoon-2559330a-3d47-3c7f-96ef-d917101d7b5d"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le r&acirc;le et de la poule sultane</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, H&eacute;o (Ouv&eacute;a), 1997, Valentine Ouckeiwen, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p> Cette &quot;histoire de b&ecirc;tes&quot; illustre les modes de subsistance de deux oiseaux de Nouvelle-Cal&eacute;donie, le r&acirc;le et la poule sultane.</p>
      <p class="intertitre"><a name="chiefdoms"></a><a href="../corpus/show_text.php?id=cocoon-2f70b648-b0d8-3427-b55d-608011b90a5b&idref=cocoon-6f910ef4-9e21-33e8-b6b7-476109381a5f"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Origine des chefferies polyn&eacute;siennes d'Ouv&eacute;a (Iles Loyaut&eacute;)</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, W&eacute;n&eacute;ki (Ouv&eacute;a), 1997, Amédée Nahyet, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>    Plusieurs migrations polyn&eacute;siennes &agrave; Ouv&eacute;a, provenant, si l'on en croit la tradition orale, principalement de Wallis (dont le nom wallisien est justement Uvea), ont vraisemblablement eu lieu entre le XVIe et le XVIIIe si&egrave;cle. Le pr&eacute;texte donn&eacute; dans ce r&eacute;cit &agrave; cette migration est le d&eacute;sir d'aventure, de d&eacute;couverte d'autres terres. Dans d'autres versions, les raisons &eacute;voqu&eacute;es sont semblables &agrave; celles expliquant la migration tongienne &agrave; Lifou : le fils d'un chef de Wallis est bless&eacute; ou tu&eacute; lors de la construction de pirogues, les coupables prennent la fuite pour &eacute;viter des repr&eacute;sailles. La pr&eacute;diction permettant de reconna&icirc;tre l'&icirc;le &agrave; atteindre (poisson-mulet sautant au-dessus des feuilles de pal&eacute;tuvier) et le message d'adieu &eacute;mis par l'esprit d'une femme wallisienne sont tr&egrave;s souvent &eacute;voqu&eacute;s &agrave; Ouv&eacute;a. Dans le nord d'Ouv&eacute;a, les Polyn&eacute;siens ont &eacute;t&eacute; accueillis par le grand chef iaai Bazit, d&eacute;sireux de s'en faire des alli&eacute;s contre ses rivaux traditionnels. Les noms des chefs polyn&eacute;siens auraient &eacute;t&eacute; modifi&eacute;s apr&egrave;s leur installation &agrave; Ouv&eacute;a : Kaukelo, Peka et Atunai seraient devenus respectivement Nekelo, Beka, et Drumai. Les descendants de cette migration parlent le fagauvea, langue polyn&eacute;sienne, qui au contact du iaai s'est enrichi (phonologie et vocabulaire).</p>
      <p class="intertitre"><a name="KingfisherBuzzard"></a><a href="../corpus/show_text.php?id=cocoon-7138b97b-c27e-3282-94a2-6dfe90b4b821&idref=cocoon-bab2e170-c812-3a9e-bd0c-3f802f4bfc9d"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le martin-p&ecirc;cheur et la buse</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
Nouvelle-Cal&eacute;donie, W&eacute;n&eacute;ki (Ouv&eacute;a), 1997, Amédé Nayet, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p> Cette &quot;histoire de b&ecirc;tes&quot;, &agrave; caract&egrave;re all&eacute;gorique, symbolise la r&eacute;partition des t&acirc;ches dans les plantations. Le martin-p&ecirc;cheur, au beau plumage, se montre le jour et veille &agrave; la pr&eacute;paration des petites buttes, les &quot;taupini&egrave;res&quot;, o&ugrave; sont enterr&eacute;s les tubercules d'igname esculenta, les &quot;walei&quot;. La buse, au plumage terne et sombre, travaille de nuit &agrave; attacher les tiges des jeunes pousses d'igname avant d'annoncer le lever du jour. Le canard sauvage, oiseau de for&ecirc;t noir et blanc, r&eacute;gule le travail des deux autres en annon&ccedil;ant le beau ou le mauvais temps.</p>
      <p class="intertitre"><a name="Ohnyat"></a><a href="../corpus/show_text.php?id=cocoon-79d55f71-559d-393b-8f23-0f5894f89b22&idref=cocoon-8a97960e-7a79-3a98-95b2-0e7271190036"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">La pierre du vent &agrave; Ohnyat</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, W&eacute;n&eacute;ki (Ouv&eacute;a), 1997, Amédé Nayet, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p> Ce r&eacute;cit &eacute;voque les alliances qui perdurent entre les &icirc;les d'Ouv&eacute;a et de Lifou, par l'interm&eacute;diaire du clan Hnadruao &agrave; Ohnyat, originaire du village de Unatr&euml; &agrave; Lifou, et auquel appartient la famille Drehudrohu et son ma&icirc;tre du vent. On fait appel &agrave; ce dernier lorsque l'on veut b&eacute;n&eacute;ficier de vents favorables pour gagner l'&icirc;le de Lifou, ou, plus prosa&iuml;quement, se d&eacute;barrasser des moustiques, bien envahissants par temps chaud et lourd. Il existerait aussi, entre Ouv&eacute;a et Lifou, un r&eacute;cif aupr&egrave;s duquel les gens de Ohnyat voulant se rendre &agrave; Lifou, leur &icirc;le d'origine, feraient en passant un geste coutumier. </p>
      <p class="intertitre"><a name="Aneua"></a><a href="../corpus/show_text.php?id=cocoon-e472f6b2-bfbc-3a38-b276-f262dabb65cc&idref=cocoon-8919fab1-8d22-39f4-bd01-5aff953a9fd9"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le trou d'eau d'Aneua</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, W&eacute;n&eacute;ki (Ouv&eacute;a), 1997, Jean-Marie Ngavit, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p> Ce r&eacute;cit, pr&eacute;sent&eacute; comme v&eacute;ridique, relate la mort tragique d'un jeune homme, qui, pouss&eacute; par son orgueil, voulut s'attirer l'admiration de ses camarades en pariant trop sur ses capacit&eacute;s physiques.</p>
      <p class="intertitre"><a name="Motutapu"></a><a href="../corpus/show_text.php?id=cocoon-252930b1-d8ec-3d8c-9d99-b831d0c64a55&idref=cocoon-f41d709d-3b20-38f5-a29e-6a76adc65193"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">L&eacute;gende de la femme de Motutapu</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Mouli (Ouv&eacute;a), 1997, Paul Mitcham, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Heo (Beautemps-Beaupr&eacute;), Motutapu, Motuone et Bunaaca font partie d'un petit archipel, actuellement inhabit&eacute;, situ&eacute; au nord-ouest des Pl&eacute;&iuml;ades du nord, ces derni&egrave;res fermant, avec les Pl&eacute;&iuml;ades du sud, le lagon d'Ouv&eacute;a. La d&eacute;esse Logoti aurait fui Heo et les mauvais traitements que lui infligeaient ses habitantes, sales et bruyantes, pour se r&eacute;fugier &agrave; Motutapu. Pour cette raison, les femmes et les chefs ne peuvent se rendre &agrave; Motutapu aujourd'hui.</p>
      <p class="intertitre"><a name="Bebea"></a><a href="../corpus/show_text.php?id=cocoon-e72a41ea-6e5e-318f-994f-4079def5b878&idref=cocoon-6b256130-b97f-37a3-832c-9d597d0e0e2f"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Histoire de Bebea</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Mouli (Ouv&eacute;a), 1997, Lazare Wegué, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Un rocher de forme arrondie est situ&eacute; sur l'&icirc;lot Dengala (appel&eacute; parfois &quot;&icirc;le Haute&quot;) &agrave; l'est de l'&icirc;le Angen, dans l'archipel des Pl&eacute;&iuml;ades du nord. Ce rocher est en fait un jeune homme, nomm&eacute; Bebea ou Ameti. Curieux des bruits qui lui parvenaient de la &quot;grande &icirc;le&quot; (Heo ou Angen ?), le jeune homme obtint de sa grand-m&egrave;re la possibilit&eacute; de s'y rendre : en fait, il s'agissait du pays des morts et, bien qu'enduit de jus de crabe, le jeune homme se fit rep&eacute;rer comme &eacute;tranger au cours de la danse des morts. Son incursion au pays des morts lui valut de regagner, p&eacute;trifi&eacute;, son &icirc;lot d'origine.</p>
      <p class="intertitre"><a name="Muli"></a><a href="../corpus/show_text.php?id=cocoon-36c03d71-a517-37f2-80f8-983276c00d0f&idref=cocoon-5e678d83-fab9-363d-89f6-859b4cb57de9"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">L'arriv&eacute;e d'Atunai &agrave; Mouli</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Noum&eacute;a, Vall&eacute;e du Tir, 1997, Marie-Josèphe Drumai, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Ce texte propose une explication &agrave; la migration polyn&eacute;sienne vers Ouv&eacute;a (&icirc;les Loyaut&eacute;), provenant, si l'on en croit la tradition orale, principalement de Wallis/Uvea, et qui eut lieu vraisemblablement entre le XVIe et le XVIIIe si&egrave;cle. Le pr&eacute;texte donn&eacute; dans ce r&eacute;cit est l'accident dont aurait &eacute;t&eacute; victime le fils d'un chef de Wallis au cours de travaux de construction de pirogues, les coupables prenant ensuite la fuite pour &eacute;viter des repr&eacute;sailles. Le message d'adieu d'une vieille femme wallisienne expliquant aux fuyards comment reconna&icirc;tre leur destination finale - l'&icirc;le avec un poisson mulet sautant par dessus une feuille de pal&eacute;tuvier - est transmis &agrave; l'identique dans plusieurs autres versions. Cependant, le r&eacute;cit de Drumai, Marie-Jos&egrave;phe est original en ce sens que sont associ&eacute;s une feuille d'arbre et un poisson diff&eacute;rents pour chacun des points de chute des trois chefs wallisiens Nekelo (anciennement Kaukelo), Peka (Beka) et Atunai, qui deviendra Drumai. A Wallis m&ecirc;me, la tradition orale a conserv&eacute; le nom de la vieille femme - Sogotautau, qui serait sortie de son tombeau pour d&eacute;livrer son message au moment o&ugrave; les fuyards quittaient l'&icirc;le par la passe d'Avatolu -, et le nom de la pirogue des fuyards, Ifilaupakola. Frimigacci (Un poisson nomm&eacute; Uvea : &eacute;l&eacute;ments d'ethnohistoire de Wallis, Noum&eacute;a, CTRDP) date le d&eacute;part de cette pirogue vers les ann&eacute;es 1750. L'auteur de ce r&eacute;cit est la fille de l'ancien chef de Mouli, Carolo Drumai, qui, n'ayant pas eu de fils, a confi&eacute; la chefferie &agrave; son neveu Pierre Drumai.</p>
      <p class="intertitre"><a name="Drumai"></a><a href="../corpus/show_text.php?id=cocoon-b3fa84d8-d5bf-34b2-9f39-26b33e4ae3f1&idref=cocoon-86ffdd88-038e-3736-bde7-7d537033ce05"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">L'origine du nom &quot;Drumai&quot;</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Noum&eacute;a, Vall&eacute;e du Tir, 1997, Marie-Josèphe Drumai, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p>Ce mythe relate une alliance entre une femme originaire de la Grande Terre (selon les versions, de Petit-Couli ou de Kouaoua) et la chefferie Atunai de Mouli, d'origine wallisienne. Cette femme serait arriv&eacute;e enceinte &agrave; Mouli dans le ventre d'une baleine qu'elle aurait r&eacute;ussi &agrave; faire &eacute;chouer en lui grattant l'int&eacute;rieur du ventre avec une coquille de kuku, sorte de coquillage utilis&eacute; pour r&acirc;per les tubercules, et dont les femmes ne se s&eacute;parent pas. L'enfant de cette femme serait devenu, sous le nom de Drumai, le chef de Mouli. J. Guiart (1963, Structure de la chefferie en M&eacute;lan&eacute;sie du sud, Institut d'ethnologie du Mus&eacute;e de l'Homme) pr&eacute;sente une autre version de ce mythe, recueillie dans la r&eacute;gion de Poindimi&eacute; : le clan Nebay de la Grande Terre serait en fait &agrave; l'origine des Dumay, dont l'anc&ecirc;tre aurait &eacute;t&eacute; aval&eacute; avec sa m&egrave;re, &eacute;pouse du chef Dumay, par un requin, alors qu'elle traversait la rivi&egrave;re Kouaoua.</p>
      <p class="intertitre"><a name="HermitCrab_CoconutCrab"></a><a href="../corpus/show_text.php?id=cocoon-255a64f3-013a-35d8-b7f5-eec137bcfe7d&idref=cocoon-8fe0ae86-e0af-3cde-a9b1-503d99f5e97b"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Les deux bernard-l'hermite et le crabe de cocotier</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="up" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Ohnyat (Ouv&eacute;a), 1997, Félicien Idakote, <a href="../../membres/moyse.htm">Claire Moyse-Faurie</a></p>
      <p> Voil&agrave; pourquoi, aujourd'hui,  le bernard-l'hermite se cache dans les coquilles vides qu'il trouve, alors que le crabe de cocotier n'a pas honte de se promener tout nu.</p>
      </div>
</body>
</html>