 <div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
            <div class="page-header"><h1><a name="up"></a>Numee corpus </h1>
            <div class="text-left">
      <p class="intertitre">&nbsp;</p>
      <p class="intertitre"><a href="../../ALC/Languages/Numee_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false"><img src="../images/icones/info.gif" alt="a" width="15" height="15" border="0">Numee</a>: a brief note </p>
      <p>&nbsp;</p>
      <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Numèè&aff=Numèè" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <ul class="liste-liens">
        <li><a href="#fille">The Girl from Mont Dore</a></li>
        <li><a href="#rat">The Rat, the Sultan&rsquo;s Fowl and the Squid</a></li>
        <li><a href="#histoire">The History of the Angw&egrave;r&egrave;r&egrave;s</a></li>
        <li><a href="#Ketiware">Ketiware and the Girl from Goro</a></li>
        <li><a href="#guerre">The War between the Drojis and the Draames</a></li>
        <li><a href="#faucon">The Falcon from Ouen Island</a></li>
        <li><a href="#Vendegou">The Vendegous&rsquo; Arrival on the &Icirc;le des Pins</a></li>
        <li><a href="#aigle">The Son of the Fisher Eagle</a></li>
      </ul>
      <p>&nbsp;</p>
      <p class="intertitre"><a name="fille"></a><a href="../corpus/show_text_en.php?id=cocoon-1d86a096-2aed-3545-b0f8-a1782c2ce482&idref=cocoon-11bbdae6-e42d-3e5c-b108-badef17bd970"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Girl from Mont Dore</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
        New Caledonia, 1962, Philippe Betoe, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">This lovely legend recounted by Philippe B&eacute;to&eacute; from Ouen Island, was recorded in 1962 by Andr&eacute; G. Haudricourt. Its transcription and translation were established using Haudricourt&rsquo;s notes and the recording presented here, a passage of which has become practically inaudible. Just after sentence 92, two and a half minutes of the narration were therefore cut out. Luckily, the passage consisted in repetitions of a single scene (the heroine calling towards her two visitors from the &Icirc;le des Pins). Its suppression does not interfere with comprehension and does not alter the quality of the text as a whole.</p>
      <p class="ZonePrint">[summary] Two men from the &Icirc;le des Pins come by canoe to seek the hand of a girl from Mont Dore. This union, they argue, would bring about a new era of exchanges and visits between the two allianced chiefdoms. Alas, the undertaking turns into a disaster before the girl from Mont Dore even leaves the shores of the Grande Terre. Both her own acquaintances and in those of her husband, create obstacles, and aggressions crop up to prevent the union from being completed.</p>
      <p class="intertitre"><a name="rat"></a><a href="../corpus/show_text_en.php?id=cocoon-2facf295-f9c4-3bff-816d-c30606a739d2&idref=cocoon-78ee041a-ce97-3ff6-9294-c3eeddbb9b5b"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Rat, the Sultan&rsquo;s Fowl and the Squid</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
        New Caledonia, 1962, Charles Atiti, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">This story was told by Charles Atiti in Goro in 1962. It was recorded by A. G. Haudricourt and was transcribed and translated in Paris by J. C. Rivierre with the help of Isaac Vend&eacute;gou, and recently revised with the help of Cl&eacute;ment Vend&eacute;gou. The twistings and turnings of this famous story are here located in Lar&eacute; and Tiga, as if, for the teller, the story were part of the Loyalty Islands&rsquo; folklore. In this version, the moral of this &ldquo;legend&rdquo; is clearly reaffirmed: the rat saves the life of the sultan fowl who, with no further ado, abandons it on the spot. The squid then saves the rat, who continuously makes fun of it for its personal appearance. Indeed, in the domain of helping others, it is best not to do too much.. </p>
      <p class="intertitre"><a name="histoire"></a><a href="../corpus/show_text_en.php?id=cocoon-c7c4cee9-7762-3080-a7df-05f2d821971a&idref=cocoon-77cbbab0-fd49-341e-a4c7-a224d3a92ee6"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The History of the Angw&egrave;r&egrave;r&egrave;s</a><br>
        New Caledonia, 1966, Roch Angwèrèrè, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p>This history of the Angw&egrave;r&egrave;r&egrave;s is told by Roch Angw&egrave;r&egrave;r&egrave;, in Goro, in 1966. The tumultuous history of this lineage, exiled from Mont Dore at the beginning of colonization, also portrays the clans from Ouen island, the &Icirc;le des Pins and Goro island. The narrator recalls, in the presence of Chief Charles Atiti, the circumstances of his arrival on Goro, at the origin of his current status within the local society. The story reveals, in an exemplary manner, the strategies, changes in status and acceptance mechanisms which come into play because of these displacements, either forced or voluntary, of clans to new territories.</p>
      <p class="intertitre"><a name="Ketiware"></a><a href="../corpus/show_text_en.php?id=cocoon-f6ebd439-7145-3d40-aee4-c7456f740471&idref=cocoon-42a6714e-c328-3e88-90b1-9340d06994c3"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Ketiware and the Girl from Goro</a><br>
        New Caledonia, 1966, Roch Angwèrèrè, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">One must remember that the Lifou chiefdom is largely represented in southern New Caledonia, and more particularly by the Vend&eacute;gous who became chiefs in the &Icirc;le des Pins several centuries ago (cf. the text &quot;La venue des Vend&eacute;gou &agrave; l'&icirc;le des Pins&quot;). This story - which must be understood within these relations - was told in Goro in 1966 by Roch Angw&egrave;r&egrave;r&egrave;. It is well known in the south of the Grande Terre and several versions have been collected in the two languages of the Drubea-Kapone area.</p>
      <p class="ZonePrint">[summary]  The fame of K&eacute;tiwar&eacute;, chief of Lifou, attracted droves of marriage candidates from the Loyalty Islands and the Grande Terre. But approaching this hero turned out to be a course littered with obstacles as, living in a banyan tree under the appearance of a snake (blackbanded sea krait), he would only come out to terrify those who came to visit him. Only the girl from Goro had the necessary knowledge and help to get the better of K&eacute;tiwar&eacute;.</p>
      <p class="intertitre"><a name="guerre"></a><a href="../corpus/show_text_en.php?id=cocoon-fa92fc47-56f8-3d04-bcf7-9335d67a7284&idref=cocoon-b6a9d6b7-2541-33e3-b9ae-da619d718ff6"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The War between the Drojis and the Draames</a><br>
        New Caledonia, 1966, Apollonie Womwâ, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">This short account well illustrates the nguma told in the far south of the Grande Terre. Most of these texts are about the interclannic conflicts which preceded and accompanied, in the 19th century, the beginnings of colonization. Are mentioned in particular the wars of chief A-Draam&ecirc;, his challenges to the chiefdom of Pa&iuml;ta, or, as here, his troubles with his neighbors on the south east coast. The scattering of the Drojis who formerly inhabited the Unya region is recounted here by one of the clan&rsquo;s descendents. In this account, in the Ouen Island dialect, recorded in Goro in 1966, the narrator (Apollonie Womw&acirc;) gives only the essential elements and only very elusively mentions, towards the end of her story, the role played by the chiefdom of the &Icirc;le des Pins in the obliteration of part of the members of her clan.</p>
      <p class="intertitre"><a name="faucon"></a><a href="../corpus/show_text_en.php?id=cocoon-a3c78a17-1f0e-314c-889f-f38d8649af0c&idref=cocoon-20944939-711e-3718-94de-057d1e60b9a2"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Falcon from Ouen Island</a> <a href="#up"><img src="../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
        New Caledonia, 1966, Apollonie Womwâ, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">The story of the falcon from Ouen Island was told in 1966 by Apollonie Womw&acirc; while this speaker from Ouen Island was staying in Goro with her husband, chief Antoine Wapar&egrave; W&ecirc;r&ecirc;. The narrator gives a somewhat shortened version of this story, usually filled with more detail, which had already been collected in similar form from several different locations on the east coast of the Grande Terre.</p>
      <p class="ZonePrint">[summary]  The &ldquo;Streaked Fantail&rdquo; bird (<em>Rhipidura spilodera verreauxi</em>), the chiefdom&rsquo;s auxiliary, helps the Peregrine Falcon (<em>Falco peregrinus nesiotes</em>), inhabitant of the high summits, to recuperate his goods stolen during an incursion from the sea. Here &ldquo;Falcon of the false mango (<em>Cerbera</em>) mountain&rdquo; is the victim of Wak&ocirc;do, the presiding genie of the place called Jokuru, a reef situated off shore from Ouen Island, in the direction of the &Icirc;le des Pins. Wak&ocirc;do, it is said, is sometimes visible in the form of a shark who is a lucky omen when preceding a canoe but an evil omen when following it. The &ldquo;Streaked Fantail&rdquo; bird&rsquo;s feat earned it the honor of being distinguished among the feathered beings. The burning down of the aggressor&rsquo;s hut is said to be the cause of the fog often visible over the Jokuru reef...</p>
      <p class="intertitre"><a name="Vendegou" id="Vendegou"></a><a href="../corpus/show_text_en.php?id=cocoon-c32fd5c0-fa15-3e03-82ea-b4ce344f9612&idref=cocoon-0e0e61e4-63f6-3a8b-90ed-07522d4dfc34"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Vendegous&rsquo; Arrival on the &Icirc;le des Pins</a><br>
        New Caledonia, 1966, Alexis Vendegou, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">This account of the Vend&eacute;gou&rsquo;s arrival on the &Icirc;le des Pins was told in Touaourou in 1966 by Alexis Vend&eacute;gou, the eldest member of the branch of the clan living in the south east of the Grande Terre. The narrator recalls several essential facts concerning the chiefdom of the &Icirc;le des Pins, which, as is known since the publication of Father Lambert [Lambert P., <em>Moeurs et superstitions des N&eacute;o-Cal&eacute;doniens</em>, Noum&eacute;a, Nouvelle Imprimerie Noum&eacute;enne, 1900, 367 p., 65 gravures], was founded by Pil&eacute; K&eacute;tiwar&eacute; and his companions who came from Lifou by canoe. This narrative presents the relation between this spectacular arrival and the early successes of these newcomers, especially their winning a surfing contest which was underway when they arrived. The kinship between the name Vend&eacute;gou and that of a Mou (Lifou) chief lineage is proof, according to the narrator, of the tradition&rsquo;s truth. However, more yet than in Father Lambert&rsquo;s account, it is the physical aspect and the beauty of the visitors which is stressed, the fact that they made up a &ldquo;separate people&rdquo; which intrigued and delighted their hosts.</p>
      <p class="intertitre"><a name="aigle"></a><a href="../corpus/show_text_en.php?id=cocoon-f173e913-8eab-3972-814e-db3a10a7191b&idref=cocoon-6207ad49-5509-392c-8cdd-976876cb603f"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">The Son of the Fisher Eagle</a><br>
        New Caledonia, Touaourou, 1966, Marguerite Ati, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">This story belongs to the type concerning children &ldquo;conceived in the bush&rdquo;, richly illustrated in the New Caledonian oral literature. Several examples of this kind of story can be found in the collection of Kanak Stories [Bensa A. et Rivierre J.-C. : <em>Histoires canaques</em>, Paris, cilf (&quot;Fleuve et Flamme&quot;, textes bilingues), 1983, 159 p.] devoted to the oral texts of northern central Grande Terre. In these stories, the child born of nature soon returns to the bush or, as here, commits suicide in order to reach the land of the dead, after having shed his ornaments and his weapons. As if unnatural alliances and breaking social rules could only have a tragic outcome.</p>
      <p class="ZonePrint">[summary]  A woman from the hinterland goes to the seashore one day, where she hears a noise but cannot determine its origin. On the shore, she eats a fish caught by an eagle, becomes pregnant and gives birth to a boy. The child is soon covered with insults by her for transgressing taboos and breaking the rules of society. Their argument and their despair lead them both to their death.</p>
      </div>
</body>
</html>