 <div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
           <div class="page-header"><h1><a name="up"></a>Corpus num&egrave;&egrave;</h1></div>
           <div class="text-left">
      <p class="intertitre">&nbsp;</p>
      <p class="intertitre">Fiche technique sur le <a href="../../ALC/Languages/Numee_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false">num&egrave;&egrave;<img src="../../images/icones/info.gif" alt="a" width="15" height="15" border="0"></a></p>
      <p>&nbsp;</p>
      <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Numèè&aff=numèè" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <ul class="liste-liens">
        <li><a href="#fille">La fille du mont Dore</a></li>
        <li><a href="#rat">Le rat, la poule sultane et le poulpe</a></li>
        <li><a href="#histoire">Histoire des Angw&egrave;r&egrave;r&egrave;</a></li>
        <li><a href="#Ketiware">Ketiware et la fille de Goro</a></li>
        <li><a href="#guerre">La guerre des Droji et des Draame</a></li>
        <li><a href="#faucon">Le faucon de l'&icirc;le de Ouen</a></li>
        <li><a href="#Vendegou">La venue des Vendegou &agrave; l'&icirc;le des Pins</a></li>
        <li><a href="#aigle">Le fils de l'Aigle p&ecirc;cheur</a></li>
        </ul>
      <p>&nbsp;</p>
      <p class="intertitre"><a name="fille"></a><a href="../corpus/show_text.php?id=crdo-KDK_DORE_SOUND&idref=crdo-KDK_DORE"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">La fille du mont Dore</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Goro, 1962, Philippe Betoe, André-Georges Haudricourt</p>
      <p class="ZonePrint">Cette belle l&eacute;gende a &eacute;t&eacute; enregistr&eacute;e en 1962 par Andr&eacute; G. Haudricourt aupr&egrave;s de Philippe B&eacute;to&eacute;, de l'&icirc;le Ouen. Sa transcription et sa traduction ont &eacute;t&eacute; &eacute;tablies &agrave; partir des notes d'Haudricourt et de l'enregistrement pr&eacute;sent&eacute; ici, dont un passage est devenu quasi inaudible. Juste apr&egrave;s la phrase 92, deux minutes trente de cette narration ont donc &eacute;t&eacute; retranch&eacute;es. Heureusement, ce passage consiste en r&eacute;p&eacute;titions de la m&ecirc;me sc&egrave;ne (appels de l'h&eacute;ro&iuml;ne en direction de ses deux visiteurs de l'&icirc;le des Pins). Sa suppression ne g&ecirc;ne pas la compr&eacute;hension et n'alt&egrave;re pas la qualit&eacute; de l'ensemble du texte.<br>
        [r&eacute;sum&eacute;]  Deux hommes de l'&icirc;le des Pins viennent en pirogue pour demander la main de la fille du Mont Dore. Cette union inaugurera, disent-ils, une &egrave;re d'&eacute;changes et de visites entre les deux chefferies alli&eacute;es... H&eacute;las ! l'entreprise tourne au d&eacute;sastre avant m&ecirc;me que la fille du Mont Dore n'ait quitt&eacute; les rivages de la Grande Terre. Tant dans son voisinage que dans l'entourage de son mari, obstacles et agressions surgissent qui emp&ecirc;chent cette union d'aboutir. </p>
      <p class="intertitre"><a name="rat"></a><a href="../corpus/show_text.php?id=crdo-KDK_RAT_SOUND&idref=crdo-KDK_RAT"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le rat, la poule sultane et le poulpe</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Goro, 1962, Charles Atiti,  André-Georges Haudricourt</p>
      <p class="ZonePrint"> Cette histoire a &eacute;t&eacute; racont&eacute;e par Charles Atiti, &agrave; Goro, en 1962. Enregistr&eacute;e par André G. Haudricourt, elle a &eacute;t&eacute; transcrite et traduite &agrave; Paris par J.C. Rivierre avec l'aide d'Isaac Vend&eacute;gou, puis revue r&eacute;cemment avec le concours de Cl&eacute;ment Vend&eacute;gou. Les p&eacute;rip&eacute;ties de cette histoire c&eacute;l&egrave;bre se situent ici &agrave; Mar&eacute; et &agrave; Tiga, comme si, pour le conteur, l'histoire faisait partie du folklore des Loyaut&eacute;. Dans cette version, la morale de cette &quot;l&eacute;gende&quot; est clairement r&eacute;affirm&eacute;e : le rat sauve la vie de la poule sultane qui, sans plus attendre, l'abandonne sur place. Le poulpe sauve &agrave; son tour le rat, lequel n'a que moqueries pour son aspect physique. D&eacute;cid&eacute;ment, dans le domaine de l'entraide, il n'est pas recommand&eacute; d'en faire trop... </p>
      <p class="intertitre"><a name="histoire"></a><a href="../corpus/show_text.php?id=crdo-KDK_HIST_SOUND&idref=crdo-KDK_HIST"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Histoire des Angw&egrave;r&egrave;r&egrave;</a><br>
      Nouvelle-Cal&eacute;donie, Goro, 1966, Roch Angwèrèrè, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p>L'histoire des Angw&egrave;r&egrave;r&egrave; a &eacute;t&eacute; racont&eacute;e &agrave; Goro, en 1966, par Roch Angw&egrave;r&egrave;r&egrave;. L'histoire mouvement&eacute;e de ce lignage, chass&eacute; du Mont Dore au d&eacute;but de la colonisation, met aussi en sc&egrave;ne des clans de l'&icirc;le Ouen, de l'&icirc;le des Pins et de Goro. Le narrateur rappelle, en pr&eacute;sence du chef Charles Atiti, les circonstances de son arriv&eacute;e &agrave; Goro, d'o&ugrave; d&eacute;coulent son r&ocirc;le et son statut au sein de la soci&eacute;t&eacute; locale. L'histoire r&eacute;v&egrave;le de fa&ccedil;on exemplaire les strat&eacute;gies, changements de statuts et m&eacute;canismes d'accueil qui entrent en jeu lors de ces d&eacute;placements, forc&eacute;s ou volontaires, d'un clan vers de nouveaux terroirs.</p>
      <p class="intertitre"><a name="Ketiware"></a><a href="../corpus/show_text.php?id=crdo-KDK_GORO_SOUND&idref=crdo-KDK_GORO"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Ketiware et la fille de Goro</a><br>
      Nouvelle-Cal&eacute;donie, Goro, 1966, Roch Angwèrèrè, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Rappelons que cette chefferie de Lifou est fortement repr&eacute;sent&eacute;e dans le sud de la Nouvelle-Cal&eacute;donie, plus particuli&egrave;rement par les Vend&eacute;gou devenus chefs de l'&icirc;le des Pins voici plusieurs si&egrave;cles (<em>cf</em>. le texte &quot;La venue des Vend&eacute;gou &agrave; l'&icirc;le des Pins&quot;). Cette histoire – qui doit &ecirc;tre comprise dans le cadre de ces relations – a &eacute;t&eacute; racont&eacute;e &agrave; Goro en 1966 par Roch Angw&egrave;r&egrave;r&egrave;. Elle est bien connue dans le sud de la Grande Terre et il en existe plusieurs versions recueillies dans les deux langues de l'aire Drubea-Kapone.<br>
        [r&eacute;sum&eacute;]  La renomm&eacute;e de K&eacute;tiwar&eacute;, chef de Lifou, attire des pr&eacute;tendantes venues des Loyaut&eacute; et de la Grande Terre. Mais approcher ce h&eacute;ros s'av&egrave;re un parcours sem&eacute; d'obstacles puisque, vivant dans un banian sous l'apparence d'un serpent (&quot;tricot ray&eacute;&quot;), il ne se manifeste que pour terrifier celles qui viennent le visiter. Seule la jeune fille venue de Goro dispose des connaissances et des appuis qui lui permettent de circonvenir K&eacute;tiwar&eacute;. </p>
      <p class="intertitre"><a name="guerre"></a><a href="../corpus/show_text.php?id=crdo-KDK_GUERRE_SOUND&idref=crdo-KDK_GUERRE"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">La guerre des Droji et des Draame</a><br>
      Nouvelle-Cal&eacute;donie, Goro, 1966, Apollonie Womwâ, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Ce bref r&eacute;cit est une bonne illustration des nguma racont&eacute;s dans l'extr&ecirc;me sud de la Grande Terre. La plupart de ces textes se rapportent aux conflits interclaniques qui ont pr&eacute;c&eacute;d&eacute; et accompagn&eacute;, au XIXe si&egrave;cle, les d&eacute;buts de la colonisation. Sont &eacute;voqu&eacute;s en particulier les guerres du chef A-Draam&ecirc;, ses d&eacute;fis lanc&eacute;s en direction de la chefferie de Pa&iuml;ta, ou, comme ici, ses d&eacute;m&ecirc;l&eacute;s avec ses voisins de la c&ocirc;te sud-est. L'&eacute;parpillement des Droji install&eacute;s autrefois dans la r&eacute;gion d'Unya est racont&eacute; ici par une descendante de ce clan. Dans ce r&eacute;cit, en dialecte de l'&icirc;le Ouen, enregistr&eacute; &agrave; Goro en 1966, la narratrice (Apollonie Womw&acirc;) s'en tient &agrave; l'essentiel et n'&eacute;voque que de fa&ccedil;on tr&egrave;s allusive, vers la fin de l'histoire, le r&ocirc;le jou&eacute; par la chefferie de l'&icirc;le des Pins dans l'an&eacute;antissement d'une partie de son clan. </p>
      <p class="intertitre"><a name="faucon"></a><a href="../corpus/show_text.php?id=crdo-KDK_FAUCON_SOUND&idref=crdo-KDK_FAUCON"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le faucon de l'&icirc;le de Ouen</a> <a href="#up"><img src="../../images/icones/fleche-haut.gif" alt="a" width="10" height="9" border="0"></a><br>
        Nouvelle-Cal&eacute;donie, Goro, 1966, Apollonie Womwâ, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">L'histoire du faucon de l'&icirc;le Ouen a &eacute;t&eacute; racont&eacute;e en 1966 par Apollonie Womw&acirc;, alors que cette locutrice de l'&icirc;le Ouen s&eacute;journait &agrave; Goro avec son &eacute;poux, le chef Antoine Wapar&egrave; W&ecirc;r&ecirc;. La narratrice donne une version quelque peu abr&eacute;g&eacute;e de cette histoire d'ordinaire plus circonstanci&eacute;e, d&eacute;j&agrave; recueillie sous une forme similaire en plusieurs endroits de la c&ocirc;te est de la Grande Terre.<br>
        [r&eacute;sum&eacute;] L'oiseau &quot;L&egrave;ve-queue&quot; (<em>Rhipidura spilodera verreauxi</em>), auxiliaire de la chefferie, aide le faucon (<em>Falco peregrinus nesiotes</em>), l'habitant des sommets, &agrave; r&eacute;cup&eacute;rer ses biens vol&eacute;s lors d'une incursion venue de la mer. Ici &quot;Faucon de la montagne au faux manguier (<em>Cerbera</em>)&quot; est victime de Wak&ocirc;do, g&eacute;nie tut&eacute;laire du lieu-dit Jokuru, r&eacute;cif situ&eacute; au large de l'&icirc;le Ouen, dans la direction de l'&icirc;le des Pins. Wak&ocirc;do, serait dit-on, parfois visible sous la forme d'une requin qui porte chance lorsqu'il pr&eacute;c&egrave;de la pirogue, mais annonciateur de malheurs lorsqu'il la suit. L'exploit de l'oiseau &quot;L&egrave;ve-queue&quot; lui vaut d'&ecirc;tre distingu&eacute; maintenant parmi la gent ail&eacute;e. L'incendie de la case de l'agresseur serait, dit-on, &agrave; l'origine des brumes souvent visibles au-dessus du r&eacute;cif de Jokuru... </p>
      <p class="intertitre"><a name="Vendegou" id="Vendegou"></a><a href="../corpus/show_text.php?id=crdo-KDK_VADEKU_SOUND&idref=crdo-KDK_VADEKU"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">La venue des Vendegou &agrave; l'&icirc;le des Pins</a><br>
      Nouvelle-Cal&eacute;donie, Touaourou, 1966, Alexis Vendegou, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Ce r&eacute;cit de l'arriv&eacute;e des Vend&eacute;gou &agrave; l'&icirc;le des Pins a &eacute;t&eacute; racont&eacute; &agrave; Touaourou, en 1966, par Alexis Vend&eacute;gou, a&icirc;n&eacute; de la branche de ce clan &eacute;tablie dans le sud-est de la Grande Terre. Le narrateur rappelle quelques faits essentiels concernant la chefferie de l'&icirc;le des Pins, dont on sait, depuis l'ouvrage du P&egrave;re Lambert [Lambert P., <em>Moeurs et superstitions des N&eacute;o-Cal&eacute;doniens</em>, Noum&eacute;a, Nouvelle Imprimerie Noum&eacute;enne, 1900, 367 p., 65 gravures], qu'elle fut fond&eacute;e par Pil&eacute; K&eacute;tiwar&eacute; et ses compagnons venus en pirogue depuis Lifou. Le r&eacute;cit pr&eacute;sente une relation de cette arriv&eacute;e spectaculaire et des premiers succ&egrave;s de ces nouveaux venus, notamment leur victoire dans un concours de surf qui se d&eacute;roulait au moment de leur arriv&eacute;e. L'apparentement du nom des Vend&eacute;gou avec celui d'un lignage chef de Mou (Lifou) vient &eacute;tayer, selon le narrateur, la v&eacute;racit&eacute; de cette tradition. Toutefois, plus encore que dans le r&eacute;cit du P&egrave;re Lambert, l'accent est mis sur l'aspect physique et la beaut&eacute; des visiteurs, sur le fait qu'ils formaient &quot;un peuple &agrave; part&quot; qui intrigua et s&eacute;duisit leurs h&ocirc;tes. </p>
      <p class="intertitre"><a name="aigle"></a><a href="../corpus/show_text.php?id=crdo-KDK_KAKO_SOUND&idref=crdo-KDK_KAKO"><img src="../../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0">Le fils de l'Aigle p&ecirc;cheur</a><br>
      Nouvelle-Cal&eacute;donie, Touaourou, 1966, Marguerite Ati, <a href="../../membres/rivierre.htm">Jean-Claude Rivierre</a></p>
      <p class="ZonePrint">Cette histoire appartient  &agrave; la th&eacute;matique de l'enfant &quot;con&ccedil;u dans la brousse&quot;, richement illustr&eacute;e dans la litt&eacute;rature orale n&eacute;o-cal&eacute;donienne. Plusieurs exemples de ce genre d'histoires figurent dans le recueil <em>Histoires canaques</em> [Bensa A. et Rivierre J.-C. : <em>Histoires canaques</em>, Paris, CILF (&quot;Fleuve et Flamme&quot;, textes bilingues), 1983, 159 p.] consacr&eacute; aux textes oraux du centre nord de la Grande Terre. Dans ces histoires, l'enfant issu du monde naturel ne tarde pas &agrave; regagner la brousse ou, comme ici, &agrave; rejoindre par le suicide le monde des morts, apr&egrave;s s'&ecirc;tre d&eacute;pouill&eacute; de ses parures et de ses armes. Comme si l'alliance hors normes et le d&eacute;fi aux r&egrave;gles sociales ne pouvaient qu'&ecirc;tre sanctionn&eacute;s de la mani&egrave;re la plus tragique.<br>
        [r&eacute;sum&eacute;]  Une femme de l'int&eacute;rieur des terres se rend un jour au bord de mer, d'o&ugrave; lui parvient un bruit dont elle ne comprend pas l'origine. Sur le rivage, elle consomme un poisson p&ecirc;ch&eacute; par un aigle puis tombe enceinte et donne le jour &agrave; un gar&ccedil;on. Bient&ocirc;t l'enfant est accabl&eacute; de ses reproches et de ses insultes pour avoir transgress&eacute; ses interdits. Leur dispute et leur d&eacute;sespoir les conduisent jusqu'&agrave; la mort.      </p>
        </div>
</body>
</html>