<div>&nbsp;</div>

<html><head><meta charset="utf-8"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>
           <div class="page-header"><h1>Corpus romani</h1></div>
           <div class="text-left">
      <p class="intertitre">&nbsp;</p>
      <p class="intertitre">Fiche technique sur le <a href="../../ALC/Languages/Romani_popup.htm" target="_blank" onClick="window.open(this.href,'popupLink','width=600,height=600,scrollbars=yes,resizable=yes',1);return false">romani<img src="../images/icones/info.gif" alt="a" width="15" height="15" border="0"></a></p>
      <p align="left">&nbsp;</p>
      <h4 align="left">Ressources :</h4>
     <p align="left" class="intertitre">
      <img src="../images/images_pangloss/haut_parleur_s.png" alt="a" width="20" height="20"> <a href="../corpus/list_rsc.php?lg=Romani&aff=romani" target="_blank">Accès à toutes les ressources</a>
      </p>
       <p align="left" class="intertitre">&nbsp;</p>
      <h4 align="left">Textes romani</h4>
      <p align="left" class="intertitre"><a href="../corpus/show_text.php?id=cocoon-b48c740d-59ad-3d91-9956-fdd3ea003ba0&idref=cocoon-1330a853-7d11-346b-97c2-cd52ec8b0231"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Le pou et le Rom</a><br>
      Grèce, Thrace, Komotini, 2006, <a href="../../membres/adamou.htm">Evangelia Adamou</a></p>
      <p>C&rsquo;est l&rsquo;histoire amusante d&rsquo;un anti-h&eacute;ros rom qui &eacute;pousa la fille du roi (pour avoir reconnu un &eacute;norme pou), gagna une guerre au profit de son nouveau royaume (pour avoir suivi un chien qui lui avait vol&eacute; un morceau de viande) et fut consid&eacute;r&eacute; comme un homme sage et &eacute;rudit (pour avoir parl&eacute; en romani &agrave; une vieille mendiante rom).</p>
      <p align="left" class="intertitre"><a href="../corpus/show_text.php?id=cocoon-3c211c50-ea89-39e7-a502-67572d668627&idref=cocoon-a94769b5-8b5a-35bb-af02-130f145706b5"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> L'homme-serpent</a><br>
      Grèce, Thrace, Komotini, 2006, <a href="../../membres/adamou.htm">Evangelia Adamou</a></p>
      <p>L&rsquo;histoire de l&rsquo;homme n&eacute; sous forme de serpent est cont&eacute;e ici rapidement. L&rsquo;homme-serpent tue toutes ses &eacute;pouses successives lors de leur nuit de noces. Gr&acirc;ce &agrave; un r&ecirc;ve, la m&egrave;re d'une future &eacute;pouse peut indiquer &agrave; sa fille comment l'aider &agrave; se transformer d&eacute;finitivement en homme. Elle doit s&rsquo;habiller avec quarante et un v&ecirc;tements et en enlever un chaque fois que l&rsquo;homme-serpent enl&egrave;vera l'une de ses quarante peaux. Ainsi, apr&egrave;s avoir enlev&eacute; toutes ses peaux de serpent,  il deviendra  vraiment un bel homme.</p>
      <p align="left" class="intertitre"><a href="../corpus/show_text.php?id=cocoon-af3f71a6-b342-38e0-9707-ad82d5175fac&idref=cocoon-f4d1f3b5-7464-35d7-a716-d423146cf073"><img src="../images/icones/Txt_Inter_parchemin.jpg" alt="a" width="20" height="20" border="0"> Le couard et les g&eacute;ants</a><br>
      Grèce, Thrace, Komotini, 2006, <a href="../../membres/adamou.htm">Evangelia Adamou</a></p>
      <p>Voici une autre  occasion de raconter l&rsquo;histoire d&rsquo;un anti-h&eacute;ros rom qui est pris pour un h&eacute;ros. C&rsquo;est en effet l&rsquo;histoire du plus peureux du village, celui qui ne peut m&ecirc;me pas aller seul aux toilettes une fois la nuit tomb&eacute;e. Un soir, il tue quarante moustiques et tout fier fait inscrire sur une &eacute;p&eacute;e : &laquo; Celui qui en a tu&eacute; quarante d&rsquo;un coup&nbsp;&raquo;. Un jour, alors qu&rsquo;il dort sous un arbre, des g&eacute;ants viennent &agrave; lire cette inscription et  le kidnappent pour lui faire &eacute;pouser leur s&oelig;ur. Mais le Rom se r&eacute;v&egrave;le bien fain&eacute;ant et ils ne cherchent plus que le moyen de s&rsquo;en d&eacute;barasser. <br>
      </p>
      <h4><br>
        Le  romani </h4>
      <p>Le romani est une langue indo-aryenne. Les dialectes parl&eacute;s aujourd'hui en Gr&egrave;ce appartiennent &agrave; deux principaux groupes : le romani balkanique et le romani vlax. La pr&eacute;sence des Rom dans les Balkans est document&eacute;e depuis le XIe si&egrave;cle et s'est poursuivie jusqu'&agrave; aujourd'hui sans interruption. Les groupes vlax sont arriv&eacute;s plus r&eacute;cemment, souvent dans les ann&eacute;es 1920, apr&egrave;s le trait&eacute; de Lausanne. Le romani du quartier Anahoma de Komotini est tr&egrave;s clairement un dialecte vlax.<br>
      La ville de Komotini est c&eacute;l&egrave;bre dans les &eacute;tudes rom, car c'est l&agrave; que fut &eacute;crit le premier document romani des Balkans, en 1668, par Evliya &Ccedil;elebi,  publi&eacute; dans le recueil <em>Seyahat name </em> &quot;Le livre des voyages&quot; (voir Friedman et Dankoff, 1991)<br>
      Aujourd'hui, les hommes, les femmes et les enfants sont trilingues (romani, turc et grec). Le romani est toujours utilis&eacute; avec les enfants. Le nom de langue le plus courant est  <em>romane</em> (adv.), nom caract&eacute;ris&eacute; par la perte de la finale <em>-s</em>. Les locuteurs distinguent la langue parl&eacute;e par les anciens, consid&eacute;r&eacute;e comme une langue pure et &quot;ferm&eacute;e&quot;, alors que la jeune g&eacute;n&eacute;ration utilise un parler bilingue, romani-turc, qu'ils consid&egrave;rent comme une langue &quot;ouverte&quot;.</p>
      <h4>Identit&eacute; </h4>
      <p>La communaut&eacute; rom &agrave; Anahoma s'identifie par deux appellations caract&eacute;ristiques :<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        - la premi&egrave;re d&eacute;signe le groupe et est en relation avec le nom de la ville o&ugrave; ils vivent : ainsi, ils se nomment eux-m&ecirc;mes <em>komotin&acute;ia</em>, d'apr&egrave;s le nom grec, Komotini, ou <em>giumurdzjinalia</em> d'apr&egrave;s le turc G&uuml;m&uuml;lcine&nbsp;;<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- la seconde est en relation avec leur religion : ils s'appellent eux-m&ecirc;mes <em>xoraxan&acute;e roma</em> &quot;Rom musulmans, Rom turcs&quot;, un nom tr&egrave;s courant dans les Balkans. <em>Xoraxan&acute;e</em> fait r&eacute;f&eacute;rence &agrave; leur religion -&nbsp;musulmane, pour se diff&eacute;rencier des <em>dasikan&acute;e roma</em> &quot;Rom chr&eacute;tiens, Rom grecs&quot;. Alors que la majorit&eacute; des Rom appelle les Grecs <em>balam'e</em>, &agrave; Komotini on les nomme  <em>dasikan'e</em>. Ce nom,  g&eacute;n&eacute;ralement r&eacute;serv&eacute; aux Slaves, indique que les Roms de Komotini ont s&ucirc;rement v&eacute;cu au contact des Slaves (peut-&ecirc;tre en Bulgarie), o&ugrave; les Slaves &eacute;taient consid&eacute;r&eacute;s comme les &quot;Chr&eacute;tiens&quot; face aux Musulmans. Quand les groupes vlax arriv&egrave;rent en Thrace, o&ugrave; les Slaves sont musulmans (connus sous le nom de Pomaques), ils donn&egrave;rent le nom <em>dasikan&acute;e</em> &ndash;&nbsp;qui avait pris pour eux le sens de &quot;chr&eacute;tien&quot;&nbsp;&ndash; &agrave; la population chr&eacute;tienne locale, c'est-&agrave;-dire les Grecs.</p>
        </div>
</body>
</html>